### ISSUE TITLE
Avro Ibus prints Arabic Charecters 

### ISSUE THREAD

**Issue by krishnasut** [sarim/ibus-avro#103]
Hey Avro Team . 
I am using Arch Linux and have installed <ol> <li> git </li> <li> ibus </li> <li> libibus </li> <li>  gjs</li> </ol> and Gnome 3 . 
When i switch to Avro Phonetic , it starts to print <b> <u> Arabic charecters instead of Bengali</u> </b> . Any fix please ?

**Comment by fa7ad** [comment]
same here. did you find any solutions yet?

**Comment by Adyel** [comment]
Same problem with Manjaro (Arch dist.). Please, Solve this problem ASAP

**Comment by fa7ad** [comment]
I tried contacting @sarim on facebook too, but he didn't respond. I think its safe to say that this project is abandoned. I'm using [saon](https://sourceforge.net/projects/saon/) and [avro.im](http://avro.im) for now.

**Comment by fa7ad** [comment]
**UPDATE:**
I reached out to @sarim via email and we found a workaround. See #106

**Comment by sarim** [comment]
The workaround blogpost: http://linux.omicronlab.com/2016/09/25/fix-arch-gnome-arabic.html

**Comment by fa7ad** [comment]
Sweet! the AUR package got updated, so you don't need to do anything. It should work by default. ![music-video-2012-katy-perry-UPK4DS13VefEk](https://camo.githubusercontent.com/6b8120f1f63a6b8501eed3c228caf509067db4cc/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f55504b3444533133566566456b2f67697068792e676966>)

**Comment by krishnasut** [comment]
<layout>us</layout> trick is not working. it shows normar English character instead of bengali character. Even no suggesion pop up is showing. 
ibus version is -- ibus 1.5.14-1 
gjs version is -- gjs 1.46.0-1 
Here is the output of  /usr/share/ibus/component/ibus-avro.xml --- 
<engines>
                <engine>
                        <name>ibus-avro</name>
                        <language>bn</language>
                        <license>MPL</license>
                        <author>Sarim Khan &lt;sarim2005@gmail.com&gt;</author>
                        <icon>/usr/share/ibus-avro/avro-bangla.png</icon>
                        <layout>us</layout>  
                        <longname>Avro Phonetic</longname>
                        <description>Avro Phonetic Input Method</description>
                        <setup>/usr/bin/env gjs --include-path=/usr/share/ibus-$
                        <rank>0</rank>
                </engine>
        </engines>

Thanks in advanced.

**Comment by sarim** [comment]
If suggestion pop-up isn't showing, probably avro isn't running. check `~/.candidate-selections.json`

**Comment by fa7ad** [comment]
@krishnasut আই ক্যান স্টিল টাইপ বাংলা :confused:

**Comment by krishnasut** [comment]
কাজ করছে । থ্যাংকস ।
