### ISSUE TITLE
IBUS AVRO FOR FEDORA 27

### ISSUE THREAD

**Issue by AnupamMitra** [sarim/ibus-avro#118]
I found the guidelines for Fedora 17 only in Omicronlab site. Would it be possible to install Ibus Avro on Fedora 27?

**Comment by sarim** [comment]
Try to compile it using the README of this repo.

**Comment by AnupamMitra** [comment]
Before opening the issue here, it was done by me but of no avail. However, on your advice I followed the the guidelines again, but yet to get any result. For your ready reference the outcome is given below.

[anupam@localhost ~]$ git
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone      Clone a repository into a new directory
   init       Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add        Add file contents to the index
   mv         Move or rename a file, a directory, or a symlink
   reset      Reset current HEAD to the specified state
   rm         Remove files from the working tree and from the index

examine the history and state (see also: git help revisions)
   bisect     Use binary search to find the commit that introduced a bug
   grep       Print lines matching a pattern
   log        Show commit logs
   show       Show various types of objects
   status     Show the working tree status

grow, mark and tweak your common history
   branch     List, create, or delete branches
   checkout   Switch branches or restore working tree files
   commit     Record changes to the repository
   diff       Show changes between commits, commit and working tree, etc
   merge      Join two or more development histories together
   rebase     Reapply commits on top of another base tip
   tag        Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch      Download objects and refs from another repository
   pull       Fetch from and integrate with another repository or a local branch
   push       Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
[anupam@localhost ~]$ libibus-1.0-0
bash: libibus-1.0-0: command not found...
libibus-1.0-dev
[anupam@localhost ~]$ libibus-1.0-dev
bash: libibus-1.0-dev: command not found...
ibus
[anupam@localhost ~]$ ibus
Usage: ibus COMMAND [OPTION...]

Commands:
  engine          Set or get engine
  exit            Exit ibus-daemon
  list-engine     Show available engines
  watch           (Not implemented)
  restart         Restart ibus-daemon
  version         Show version
  read-cache      Show the content of registry cache
  write-cache     Create registry cache
  address         Print the D-Bus address of ibus-daemon
  read-config     Show the configuration values
  reset-config    Reset the configuration values
  emoji           Save emoji on dialog to clipboard 
  help            Show this information
[anupam@localhost ~]$ automake
bash: automake: command not found...
autoconf
[anupam@localhost ~]$ autoconf
bash: autoconf: command not found...
gjs
[anupam@localhost ~]$ gjs
gjs> gir1.2-gjsdbus-1.0
typein:1:4 missing ; before statement:
typein:1:4 gir1.2-gjsdbus-1.0
typein:1:4 ....^
  @<stdin>:1:34
gjs> gir1.2-ibus-1.0
typein:2:4 missing ; before statement:
typein:2:4 gir1.2-ibus-1.0
typein:2:4 ....^
  @<stdin>:1:34
gjs> git clone git://github.com/sarim/ibus-avro.git
typein:3:4 missing ; before statement:
typein:3:4 git clone git://github.com/sarim/ibus-avro.git
typein:3:4 ....^
  @<stdin>:1:34
gjs> cd ibus-avro
typein:4:3 missing ; before statement:
typein:4:3 cd ibus-avro
typein:4:3 ...^
  @<stdin>:1:34
gjs> aclocal && autoconf && automake --add-missing
typein:5:34 missing ; before statement:
typein:5:34 aclocal && autoconf && automake --add-missing
typein:5:34 ..................................^
  @<stdin>:1:34
gjs> ./configure --prefix=/usr
typein:6:0 expected expression, got '.':
typein:6:0 ./configure --prefix=/usr
typein:6:0 ^
  @<stdin>:1:34
gjs> sudo make install
typein:7:5 missing ; before statement:
typein:7:5 sudo make install
typein:7:5 .....^
  @<stdin>:1:34
gjs>

**Comment by now-im** [comment]
@AnupamMitra  what i am seeing is missing dependencies. Sometimes different linux distro keeps package in different name. You need to find it. Besides, ubuntu uses gnome as main desktop environment. So, you can try to use it instead.

**Comment by now-im** [comment]
@sarim  what about making it available in Snap package format. In that way,  every linux distro installation problem can be solved.

**Comment by AnupamMitra** [comment]
@now-im Do you mean to install Avro in Fedora 27 with the installation procedure for Ubuntu?

**Comment by AnupamMitra** [comment]
@now-im Do you mean to install Avro in Fedora 27 with the installation procedure for Ubuntu?

**Comment by now-im** [comment]
In ibus-avro home page, there is step by step instruction to compile the package.
 1. Installing listed dependencies,
 2. Running commands in terminal.

**Comment by AnupamMitra** [comment]
@now-im Did you mean http://linux.omicronlab.com/ as ibus-avro home page ?

**Comment by now-im** [comment]
@sarim Avro readme.md does not work in fedora. Some changes are needed.

**Comment by AnupamMitra** [comment]
@sarim I'm still anxiously waiting that you will provide me necessary guidelines to install ibus avro for Fedora. In the meantime, I have upgraded to Fedora 28.

**Comment by now-im** [comment]
@AnupamMitra use this wesite to type bangla and copy paste as you need. This is the only solution I can provide.

avro.im
