### ISSUE TITLE
অভ্র কাজ না করলে কি করব? 

### ISSUE THREAD

**Issue by Adyel** [sarim/ibus-avro#125]
প্রথমে নির্লজ্জের মত প্রচার চালানোর জন্য ক্ষমা চেয়ে নিচ্ছি।
আমি ধারনা করে নিচ্ছি, যারা এখানে এসেছেন তারা বেশিরভাগই কোন সমস্যায় পড়ে শেষ অবলম্বন হিসেবে এখানে বাগ রিপোর্ট করতে এসেছেন। কিন্তু অতি দুঃখের কথা হল এই প্রজেক্টটি অনেকদিন ধরে maintain হচ্ছে না। এজন্য অনেকেই সমস্যার সমাধান না পেয়ে ফিরে যাচ্ছেন। 
এর বিকল্প হিসেবে আপনারা [OpenBangla-Keyboard](https://github.com/OpenBangla/OpenBangla-Keyboard) ব্যাবহার করে দেখতে পারেন। এটি OpenSource, Unicode compliant Bengali Input Method এর একটি সফটওয়্যার, যেটি অনুপ্রেনিত হয়েছে অভ্র হতে। বর্তমানে এই কোডবেস খুবই একটিভ আর কোন সমস্যার সুম্মখিন হলে আপনারা আমদের সাথে সহজে যোগাযোগ করতে পারবেন। আপনি যদি সাধারণ/নতুন লিনাক্স ব্যাবহারকারী হন, ইন্সটল করতে সমস্যা হয় কিংবা যেকোনো প্রশ্ন থাকে আমাদের সরাসরি [Discord](https://discord.gg/HXK7QnJ) এ মেসেজ দিতে পারেন । আমারা আপনাকে সহযোগিতা করব :smile: 

সবশেষে আমি ধন্যবাদ দিতে চাই Mehdi Hasan Khan, Rifat Nabi, Sarim Khan ভাইদের । বাংলা কীবোর্ড কমিউনিটিতে আপনাদের অপূরণীয় অবদান রাখার জন্য। :bowing_man:

**Comment by m4hi2** [comment]
ভাই, ইউজার যদি ইন্সটল করতে না জানে তাহলে এখানে মেইন্টেনারের কি দোষ? 
মানে কোডবেইজে কি চেঞ্জ বা মেনটেইন করলে ইন্সটলেশনে সমস্যা হবে না তা যদি একটু বলতেন তাহলে গিট্টুবাবার সুবিধা হইত 🥇 

আমি বিভিন্ন প্রয়োজনে মানুষজনকে ওপেনবাংলা কিবোর্ড ব্যাবহার করার পরামর্শ দিয়েছি, তবে সফ্টওয়ারের বাগ রিপোর্ট করার যায়গাতে এসে এভাবে "কোডবেইজ" এর সাথে ১% ও সম্পর্ক নাই এমন কথা বার্তা বলাটা নিতান্তই দৃষ্টিকটু লাগতেছে।

**Comment by Adyel** [comment]
@m4hi2 প্রথমত আমি কোথায় maintainer এর দোষ দিচ্ছি একটু বলবেন কি? অভ্রতে এখন প্রিবিল্ড বাইনারি দেওয়া হয় না, এজন্য অনেকেরই সমস্যা হয়।

আপনি পুরাতন ইস্যুগুলা দেখলেই বুঝতে পারবেন কেন এটা পোস্ট করা হয়েছে। অনেকেই Avro এর বিকল্প Software যে আছে জানে না, যারা সমস্যায় পড়েছে সমাধান পাচ্ছে না তাদের কাছে পৌঁছাতে হলে এখানেই আসতে হবে। আর তারপরও যদি দৃষ্টিকটু / অপ্রাসঙ্গিক মনে হয় তাহলে এই Repo এর মেইনটেইনার এটাকে ডিলিট করে দিতে পারে। ধন্যবাদ।

**Comment by codefactry** [comment]
@m4hi2  আশা করি  আমার পুরো মেসেজ মন দিয়ে পড়বেন । আমরা কেউই এখানে তর্কাতর্কি করে জিততে আসি নাই।  আমি আপনার সাথে সহমত হতে পারছি না ।  আপনি বলেছেন "ভাই, ইউজার যদি ইন্সটল করতে না জানে তাহলে এখানে মেইন্টেনারের কি দোষ?” 

 অভ্র এর ইনসটলেশনের  শুরুতেই বলা আছে, নিচের কমান্ডটি দিতে ...  
`sudo apt-get install git ibus libibus-1.0-dev automake autoconf gjs gir1.2-gjsdbus-1.0 gir1.2-ibus-1.0`


উপরের কমান্ডটি দিলে লাস্ট দুটো প্যাকেজের অস্তিত্ব পায় না বলে কোন প্যাকেজই ইন্সটল হয় না আর নিচের ইরর দেখায় ... 

```
E: Unable to locate package gir1.2-gjsdbus-1.0
E: Couldn't find any package by glob 'gir1.2-gjsdbus-1.0'
E: Couldn't find any package by regex 'gir1.2-gjsdbus-1.0'
```

![avro](https://user-images.githubusercontent.com/25224876/43170385-af6bb422-8fc6-11e8-8ac5-b7121083f5ab.jpg)


কিন্তু যদি আমি শেষের ২ টা  প্যাকেজ বাদ দিয়ে নিচের মোট করে কমান্ড দেই তবে  ... বাকি প্যাকেজ গুলো ইন্সটলেশনে কোন বাঁধা পায় না । 
`sudo apt-get install git ibus libibus-1.0-dev automake autoconf gjs `


এখন আপনিই আমাকে বলেন আমি ইউজার হিসেবে কোথায় কি ভুল করছি যে আমি ইন্সটল করতে পারছি না?   যেহেতু আপনি নিজেই বলেছেন, “ইউজার যদি ইন্সটল করতে না জানে তাহলে এখানে মেইন্টেনারের কি দোষ?” প্লিজ আমার দোষটি ধরিয়ে দিন । 

আরও কথা আছে, আইবাস অভ্র কিন্তু উবুন্টু এর সর্বশেষ 14.04 পর্যন্ত সাপোর্ট করে এর পর আর সাপোর্ট নেই। ও আরেকটি কথা ইন্সটলেশনের সময় যে ইরর আসে তা নিয়ে আমি বার বার অভ্র এর বাগ পেইজে সাহায্য চেয়েও ডেভেলপারদের কোন সাহায্য পাইনি। 

**আপনার কাছে  @Adyel   ভাইয়ের এখানে পোস্ট করা দৃষ্টি কটু লেগেছে? আমার কাছে কিন্তু  গিটু  বাবা বলে  আপনার  নিজেকে গিট স্পেশালিসট হিসেবে জাহির করাই বেশি দৃষ্টি কটু মনে হয়েছে।** যদি আমি ভুল হয়ে থাকি তবে এই গিট্টু বাবা উপমা দ্বারা কি বুঝালেন একটু ব্যাখা করলে আমি বুঝতে পারতাম। 

আরও কথা আছে, মাতিন ভাইকে আপনি চেনেন নাকি চেনেন না আমি জানি না । অভ্র যে  লিনাক্সে  কাজ করে না এর জন্য উনি নিজেই এটাকে ফর্ক করে একটা ইউজেবল সমাধান দিয়েছেন। যদিও উনি এও বলেছেন যে, উনার সমাধানটি টেম্পোরারি ওয়ার্ক এরাউন্ড পার্মানেন্ট নয়। 

এখন আপনি   https://github.com/sarim/ibus-avro/issues/102  এখানে যান ... গিয়ে দেখেন সেখানে মাতিন ভাই নিজেই তার ফর্ক করা ভারর্সনটিকে প্রমোট করছেন । এরকম আরও ইস্যু পোস্ট পাবেন যেখানে উনি এই কাজটি করেছেন ।   সেখানে তিনি সবাইকে নিজের ফর্ক ভার্সনের লিঙ্ক ধরিয়ে দিচ্ছেন। 


মাতিন ভাইয়ের মত বড় মাপের ডেভেলপার  যদি বাগ রিপোর্ট করার জায়গাতে নিজেকে প্রমোট করতে লিঙ্ক দিতে পারেন তবে আদিল ভাই তা করলে সেখানে  মহাভারত কিভাবে অশুদ্ধ হয়? 

আমাদের দেশের ২ টা ছেলে অভ্র এর একটা বিকল্প তৈরির চেষ্টা করছে ...  কোথায় আপনারা তাদের এনকারেজ করবেন তা না করে উল্টো  ডিসকারেজ করতে চলে এসেছেন।  আমি মানি  OBK এখনও বেবি পর্যায়ে আছে অনেক বাগ আছে তাতে কিন্তু এই বাগ গুলো সারিয়ে তা যদি এক সময় ফুল ভার্সনে চলে আসে তবে কত মানুষের উপকার হবে? আর এটাতে তো উনাদের লাভ নাই উনারা ফ্রিতে করছেন। যা আমরা বাঙ্গালিরা নিজেরা তো করিই  না বরং অন্য কেউ করলেও আমাদের কষ্ট বেড়ে যায়...   সেলুকাস !!! বড়ই বিচিত্র ... 

দেখেন  Canonical কোম্পানি উবুন্টু ডেভেলপ করেছে । এখন আপনি যদি গুগলে   Best Linux Distro for Desktop  লিখে সার্চ দেন কয়টা অপশন পাবেন>? কম হলেও ৫০ টা ?   Zubuntu, Elementary, Linux Mint, Zorin, TrueOS  কত কি ... কিন্তু  সবচেয়ে মজার ব্যাপার হল যে যদি তাদের হিস্ট্রি চেক করেন তবে দেখবেন  Manajro  এর মত গুটি কয়েকটা বাদে আপনার খুঁজে পাওয়া ৫০টা  Distro   এর মাঝে   ৪০ থেকে ৪৫ টাই উবুন্টু থেকে ফর্ক করা। এমনকি লিনাক্সের যে Distro সবচেয়ে জনপ্রিয় সেই লিনাক্স মিন্টও উবুন্টুরই সন্তান ... 


উবুন্টু থেকে তৈরি  হয়েও সে  উবুন্টু থেকে জনপ্রিয় ... এতে কি উবুন্টুর জনপ্রিয়তা কমে গেছে? মোটেই না ... কারণ মিন্টকেও আপডেট রিলিজের জন্য সেই উবুন্টুর আশায়ই বসে থাকা লাগে ।। এই গর্ব তো উবুন্টুরই অন্য কার নয় ...  

ঠিক তেমনি  OBK-ও অভ্র এর অনেক লাইব্রেরির উপর ডিপেন্ড করে ডেভেলপ করা ... তার মানে সেও তো অভ্র এরই সন্তান ... তবে কেন হিংসা ??? 

উবুন্টু কে ফর্ক করে  সম্ভবত  প্রতিমাসে কম করে হলেও ১ টা নতুন লিনাক্স ডিস্ট্রোর জন্ম হয়। উবুন্টু যদি হিংসা করে কোন ভাবে উবুন্টু বাদে অন্য  Distro থেকে তাদের রেপো  এক্সেস অফ করে দিত বা এমন কিছু করত যাতে কেউ তাদের কাজ ব্যবহার করে আর নতুন ওএস ডেভেলপ করতে না পারে তবে ক্ষতিটা কাদের হত? হোত ইউজারদের আর উবুন্ট্রুর ডেভেলপার  Canonical  এরই। কারণ ডেস্কটপে লিনাক্সে জনপ্রিয়তা কমে যেত । 

কারণ লিনাক্স মিন্ট যদি সবচেয়ে জনপ্রিয়  Distro হয়ে থাকে তবে সেই ক্রেডিটতো  ৮০ ভাগই উবুন্টু বা  Canonical  এর। তাহলে এতে তাদের দুঃখ কোথায়?  

উবুন্টু  তাকে ফর্ক করা মিন্ট জনপ্রিয় হবার পরেও তাদের ডিস্কারেজ নয় এনকারেজই করছে ... কারণ মিন্ট জনপ্রিয়  হওয়ায় তাদের ব্যবসাপাতি কমে যায় নাই বরং বেড়েছে । কারণ মিন্টও এক টাইপ ডেবিয়ান  উবুন্টু। 

কোন কালে যদি এমন হয়ও  OBK   এর জনপ্রিয়তা অভ্রকেও ছাড়িয়ে যায় তবে সেই গর্ব একা  OBK এর    হবে না ... সেটা অভ্র এরও গর্ব কারণ সে অভ্র এর অনেক লাইব্রেরির উপর নির্ভরশীল। 

আপনি হয়তো বলবেন যে সব বুঝলাম কিন্তু উনি কেন বাগ রিপোর্ট পেইজে এই পোস্ট করেছেন ... আমার মনে হয় এত কিছু বলার পরে আপনি উত্তরটা অলরেডি  পেয়ে গেছেন ... প্লাস আমি আগেই বলেছি মাহিন ভাই যেমন, বাগ ইস্যু পোস্ট গুলায় নিজের রেপোর  লিঙ্ক দিচ্ছেন সমাধান হিসেবে। সেভাবে আদেল ভাইও সমাধান দিয়েছেন । সেই হিসেবে এটা বাগ রিপোর্ট পেইজের রুলস  মেনেই হয়েছে ...  কারণ  OBK  ও অভ্র থেকেই ফর্ক করা বলা যায় … সেও অভ্র এরই সন্তান …  

তার উপর আমি আগেই বলেছি আমি যে ইরোর গুলো পাচ্ছি সেগুলার সমাধান আমাকে কেউ দেয় নাই ... বার বার পোস্ট করেও আমি রেসপন্স পাইনি ... টোটালি ডেড ... তো আমার মত ভবিষ্যতে  আরও অনেকেই এই ইরর পাবে তো তাদের একটি সমাধান দরকার তাই না? কারণ অভ্র আইবাসের ডেভেলপারেরা তো রেস্পন্স করা অফ করে দিয়েছেন ...  

তাই আদিল ভাই একটি সমাধানই দিয়েছেন । এটা "কোডবেইজ" এর সাথে ১% ও সম্পর্ক নাই" ভুল কারণ  OBK  অভ্র এর জাভা স্ক্রিপ্ট লাইব্রেরির উপর নির্ভরশীল । আর যারা সমস্যা ফেস করবে উনি সমস্যার সমাধান তো এখানেই দিবেন নাকি অন্য কোথাও? 

এত কথা এই জন্যই বলা যে, অন্যের কাজকে এনকারেজ করুন ডিসকারেজ না । খুব সম্ভবত আপনি লিনাক্স  নয় উইন্ডোজ ইউজার এইকারণে এখনও জানেন না যে আপডেটেড লিনাক্সে আর অভ্র কাজ করে না । 

বাংলাদেশে কেউই ওপেনসোর্স প্রোজেক্টে ডেডিকেটেড হয়ে কাজ করে না । তার সবচেয়ে বড় প্রুফ অভ্র প্রোজেক্ট নইলে অভ্র আইবাস কেন আজ অনেক বছর ধরে ডেড? অথচ ইউরোপ আমেরিকায় আর এখন ওপেনসোর্স অলাভজনক প্রোজেক্ট নয় ... ফ্রি হয়েও বিলিয়ন ডলারের মার্কেট হল ওপেনসোর্স 

এমন অবস্থা সেখানে ১ কিংবা ২ দিনে আসে নাই ... সেখানকার ডেভেলপারেরা নিজের খেয়ে বনের মোষ তাড়ানোর মত কাজ করেছেন বলেই আজ সারা বিশ্বে ওপ্নেসোর্সের জয়জয়কার ... 

আমরা কেন পারছি না? কারণ আমাদের দেশে সবাই ভাবে ওপেনসোর্স মানে ফ্রি আর ফ্রি মানে জিরো ইনকাম যা এখন আর আমেরিকা ইউরোপে গেলে সত্য নয় ... উবুন্টু কি এখন আর অলাভ জনক প্রোজেক্ট? মোজিলা? ওয়ার্ডপ্রেস কিংবা জুমলা?? 

তাই আমাদের দেশের ২ জন ডেভেলপার যদি নতুন কিছু করতে এগিয়ে আসে আমি কেন কোন সাহসে বা কোন অধিকারে তাদেরকে ব্যাংগ করব জনাব গিট্টু বাবা সাহেব? 



 বিঃ দ্রঃ আমি কোনভাবেই  OBK  প্রোজেক্টের সাথে সংশ্লিষ্ট কেউ নই । আমি শুধু একটা ওপেনসোর্স প্রোজেক্টকে এগিয়ে যেতে সাপোর্ট করেছি মাত্র।

**Comment by hmsharif1998** [comment]
Ibus ছাড়া কি ফোনেটিক টাইপ করার কোন রাস্তা আছে?

**Comment by apandada1** [comment]
Now that Avro can be easily installed and configured in recent versions of Ubuntu and derivatives, can we close this?
