### ISSUE TITLE
Engine doesn't work properly when 1st layout isn't "us" (English-us)

### ISSUE THREAD

**Issue by sarim** [sarim/ibus-avro#130]
Continuation of discussion from #128 
Found some similiar issues upstream
https://bugzilla.redhat.com/show_bug.cgi?id=760108
https://github.com/ibus/ibus-m17n/commit/6c88539733be30886e93583414a2d5ca1c60743c
https://github.com/ibus/ibus/issues/1943

**Comment by sarim** [comment]
How the error manifests:
ibus-avro code expects the `state` variable in "process_key_event" to be in [0,1,16,17]. 
For example a normal keypress event sends "16". 16 translates to IBUS_MOD2_MASK: Modifier 2 (Usually Num_Lock (0x4d)) activated.

If 1st layout is English-uk, that variable probably gets another mask added as it becomes 8208.

Solve should be simple. Use bit math instead of simple `==`.

**Comment by sarim** [comment]
@AnwarShah please run `ibus-daemon` in verbose mode in terminal and screenshot/paste output of that.

**Comment by AnwarShah** [comment]
@sarim I've updated the code via ppa and that includes the patch (previous update didn't). Looks good. I can input Bangla even with this order of layouts UK -> US -> Avro

**Comment by prionkor** [comment]
ubuntu 20.04 having a similar issue.

**Comment by gunnarhj** [comment]
> ubuntu 20.04 having a similar issue.

I hope not, since the `ibus-avro` package in Ubuntu includes @sarim's fix. Exactly which version of `ibus-avro` are you using?

**Comment by prionkor** [comment]
`v1.1-3` I think `ibus-avro` was crushed. Working properly after a restart.

**Comment by gunnarhj** [comment]
That sounds good.

We have a problem with far too frequent IBus crashes in Ubuntu 20.04, which are not specific to `ibus-avro`. I have reasons to hope that we will be able to improve that soon.
