### ISSUE TITLE
Follow-ups due to the Debian/Ubuntu packaging

### ISSUE THREAD

**Issue by gunnarhj** [sarim/ibus-avro#131]
When preparing the package for Debian/Ubuntu, I made a few adjustments which I think should better be included in the upstream source.

**1. AppStream metadata file**

The package installs a `metainfo.xml` file with some basic info about the project. It's that file which makes `ibus-avro` show up in software management systems such as Ubuntu Software and GNOME Software. This is how I understand that it works in short:

* When the package is uploaded to e.g. Debian or Ubuntu, the file gets parsed and included in places like https://appstream.debian.org/ and http://appstream.ubuntu.com/

* For `ibus-avro` in eoan (19.10), the HTML file looks like [this](http://appstream.ubuntu.com/eoan/universe/metainfo/ibus-avro.html).

* The users get the info when updating the package info via `apt update`, and then e.g. GNOME Software makes use of it to present available software.

However, the `metainfo.xml` file is upstream in nature, and should be part of the upstream source. Then if for instance `ibus-avro` would be packaged for Fedora, they wouldn't need to reinvent the wheel.

**2. `.desktop` file to please gnome-control-center**

The package also installs a `.desktop` file to work around [gnome-control-center#630](https://gitlab.gnome.org/GNOME/gnome-control-center/issues/630). Until the bug has been fixed, that file is useful also for users who install Avro Phonetic via the git source.

**3. Generic name of the license file**

When setting up a [repository for the `ibus-avro` Debian package](https://salsa.debian.org/gunnarhj-guest/ibus-avro) I noticed that GitLab and GitLab based repo services (such as salsa.debian.org) only recognize certain names when looking for the license file. If it doesn't find the license file, it claims on the project page that there is no license, which is a bit annoying. I figured out a way to work around it, but the most natural fix is that the `MPL-1.1.txt` file is renamed in the upstream source to the generic name `LICENSE`.

**Comment by sarim** [comment]
Ah nice, thanks a ton. I'll check the PR soon. 👍
