### ISSUE TITLE
Autocorrect PRs

### ISSUE THREAD

**Issue by gunnarhj** [sarim/ibus-avro#133]
Hi. Me again.

In the Debian/Ubuntu package I include five tiny patches of the `autocorrect.js` file.

https://salsa.debian.org/gunnarhj-guest/ibus-avro/tree/master/debian/patches/autocorrect-fixes

Four of those mirror old pull requests at this project (#73, #74, #77, #91), and one I picked up from maateen's project (submitted as a PR here now).

@sarim, I would suggest that you consider the requests and either merge or reject. Once you have done so, I can safely drop them as patches in the package.

**Comment by sarim** [comment]
Thanks, Done :)
