### ISSUE TITLE
ibus-avro doesn't install Elementary OS

### ISSUE THREAD

**Issue by xSomoy** [sarim/ibus-avro#139]
Device Info:
### Peoblem: 
can't add "ibus-avro repository" Successfully
` Server IP: 195.135.221.134 reporting Error: 404 `

Other 2 Errors:

> 1. Err:6 http://download.opensuse.org/repositories/home:/sarimkhan/xUbuntu_14.04 ./ Release  

>2. Err:9 http://download.opensuse.org/repositories/home:/sarimkhan/xUbuntu_13.10 ./ Release

**Comment by gunnarhj** [comment]
It's unclear to me what you did to get that error message. But how about installing from the Ubuntu archive?

    sudo apt install ibus-avro

**Comment by xSomoy** [comment]
i already installed it from ubuntu  archive....  then i tried to install it manually.. is thi causing the problem?

**Comment by gunnarhj** [comment]
> i already installed it from ubuntu archive....

Ok..

> then i tried to install it manually..

May I ask why? Please note that it's the very same program.

> is thi causing the problem?

I have no idea, since you haven't explained properly what you did. Did you try to follow [this instruction](https://github.com/sarim/ibus-avro/blob/master/README.md)?

**Comment by xSomoy** [comment]
Thanks For Your Help.. im having one last problem to restarting ibus in elementary os...  can tell me how to do that in terminal. hence i couldn't find any way to restart in gui.

**Comment by gunnarhj** [comment]
I'd try

    ibus-daemon --restart

To see other available options, run

    ibus-daemon --help

**Comment by xSomoy** [comment]
everything installed properly.. but even to i switch to avro ( ctrl+space ) keyboard output still remain English

**Comment by gunnarhj** [comment]
* Do you see an indicator in the panel which shows which input method is selected?
* What's the output of this comand:

    ps a | grep avro

**Comment by xSomoy** [comment]
4548 pts/1    S+     0:00 grep --color=auto avro

**Comment by xSomoy** [comment]
tried instilling avro from "Elementary App Store" Still The Same Result. I think im failing tochange keyboard inpur method to ibus.

**Comment by gunnarhj** [comment]
Then `ibus-avro` is not started properly. I get:

     2943 tty2     Sl     0:00 gjs --include-path=/usr/share/ibus-avro /usr/share/ibus-avro/main-gjs.js     --ibus > /dev/null
    24878 pts/0    S+     0:00 grep --color=auto avro

What does this output?

    ps a | grep ibus

**Comment by xSomoy** [comment]
5861 pts/1    S+     0:00 grep --color=auto ibus

**Comment by gunnarhj** [comment]
Well, then ibus is not started at all. Try

    ibus-daemon --daemonize

then wait a few seconds, and then run those `ps` commands again.

**Comment by xSomoy** [comment]
ps a | grep avro  >>   3105 pts/0    S+     0:00 grep --color=auto avro
ps a | grep ibus   >>    3138 pts/0    S+     0:00 grep --color=auto ibus

**Comment by xSomoy** [comment]
ibus is working properly i guess.. just even tho i switched to avro it still output English. i think i can change my keyboard input method to ibus.

**Comment by xSomoy** [comment]
as i suspected my keyboard input wasn't going trough ibus... i changed it now its working properly... thanks for your valuable help. এবং শুভ সকাল . 😀😀

**Comment by xSomoy** [comment]
btw "শুভ সকাল" means good morning.. i thought you are a bengali... thanks a lo anyway

**Comment by gunnarhj** [comment]
Good that you figured it out.
