### ISSUE TITLE
Not working in Manjaro (KDE)

### ISSUE THREAD

**Issue by Sobuj53** [sarim/ibus-avro#142]
Hello,
First of all it's an honor and privilege to use Avro in any linux distro. A simple thank you is not enough to express my gratitude for this project and the developers behind it. Please accept my humble obeisances.
Anyway I've installed Ibus-Avro from AUR using Pamac manager, also installed many avro fonts as system wide. It works partially, means it works when I type in browser but not in any other window! Can you please tell me What I'm doing wrong.
Here are some info if you need, 
> DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.1.3
DISTRIB_CODENAME=Juhraya
DISTRIB_DESCRIPTION="Manjaro Linux"
KDE Plasma Version: 5.17.3

 If you need any log please inform me. I'm still noob in linux environment, so please bear with me :)

**Comment by sarim** [comment]
what is the output of  `env | grep -i im`

**Comment by Sobuj53** [comment]
Thank you for your reply. Here is what I get from running the cmd,

>XDG_RUNTIME_DIR=/run/user/1000
LC_TIME=en_US.UTF-8

**Comment by sarim** [comment]
These environment variables need to be set for ibus to work. As seen in your output, they're not set.
```
GTK_IM_MODULE=ibus
XMODIFIERS=@im=ibus
QT_IM_MODULE=ibus
```

Not sure how it is done exactly in manjaro, maybe check this? https://wiki.archlinux.org/index.php/IBus

**Comment by Sobuj53** [comment]
Thank you vai for your replay. After some trial and error I found that, if I add 

> export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

line to `~/.bashrc` file also create a `~/.xprofile` and add
`export QT_IM_MODULE=ibus` line to it; Avro will work fine in most application e.g Kate text editor, but wont work in Office 2010 (PlayOnLinux). Do you know any workaround for this issue?

**Comment by sarim** [comment]
Those issues are beyond the scope of avro, You might find the solution in wine/playonlinux support mediums.

**Comment by Sobuj53** [comment]
Thank you for your time and support.
