### ISSUE TITLE
ibus-avro suddenly stops working 

### ISSUE THREAD

**Issue by sauravgo** [sarim/ibus-avro#143]
বার বার ibus avro restart করতে হচ্ছে.
লিখতে লিখতে avro কাজ করা বন্ধ করে দিচ্ছে। তখন অভ্র icon এ ক্লিক করলেও english লেখা হচ্ছে। 
এরপর killall ibus-daemon && ibus-daemon করলে আবার অভ্র কাজ করছে ।

**Comment by sarim** [comment]
OS version? DE version?

**Comment by HattinGokbori87** [comment]
Hi, I have the same problem.
OS: Ubuntu 20.04 (Xubuntu)
DE: Xfce 4.14
The problem was also present in 19.04 & 19.10. It seems the frequency of hangs and crashes increased on 20.04.

**Comment by shahad-mahmud** [comment]
I also have the same problem. I'm currently on ubuntu 20.04 but had this problem also on Ubuntu 19.04 and 19.10

**Comment by gunnarhj** [comment]
@HattinGokbori87, @shahad-mahmud: There is indeed a problem in Ubuntu with far too frequent IBus crashes. But this project is probably not the right place to report it.

The Ubuntu developers are aware of the problem. If you have some input which might help spot the cause of the crashes, please report it at Launchpad:

    ubuntu-bug ibus

**Comment by EnigmaticJihad** [comment]
This is not only a ubuntu issue. Same in Arch Linux. I think this is an Avro issue that needs to be fixed.

**Comment by shahad-mahmud** [comment]
> This is not only a ubuntu issue. Same in Arch Linux. I think this is an Avro issue that needs to be fixed.

I also think that it is not a Ubuntu issue only. Recently I have turned into OpenBangla. It works just fine with OpenBangla and this problem does not occur.

**Comment by sarim** [comment]
Please follow the issue #156 for a possible workaround future development on the issue.
