### ISSUE TITLE
Ibus ছাড়া লিনাক্স মিন্ট এ ফোনেটিক টাইপ করার কোন উপায় আছে? 

### ISSUE THREAD

**Issue by hmsharif1998** [sarim/ibus-avro#144]
Ibus ছাড়া লিনাক্স মিন্ট এ ফোনেটিক টাইপ করার কোন উপায় আছে? বর্তমানে তো provat লে আউট সেখানে এভেইলেবল। আমি কি সেখানে ফোনেটিক লেআউট অ্যাড বা রিপ্লেস করতে পারবো? যদি হ্যাঁ হয় তাহলে সেটা কিভাবে?

**Comment by mirashif** [comment]
Avro আর maintain করা হয়না ।

OpenBangla Keyboard ব্যাবহার করুনঃ
https://github.com/OpenBangla/OpenBangla-Keyboard

**Comment by oritromax** [comment]
@mirashif Have anyone from the ibus-avro team personally told you that Avro is no longer being maintained? I don't see any 'no longer maintained' banner in the repository or any public forum. OpenBangla Keyboard is great, but why are you spamming it everywhere in this repo? Provide the solution to the actual issue.

**Comment by sarim** [comment]
As ibus-avro is in ubuntu repository and linux mint uses that, simply `apt install ibus-avro` or using any software center to install `ibus-avro` will allow you to write bangla using avro phonetic layout in linux mint.

AFAIK IBus is the de-facto standard input method technology in linux. There are some other engines other than IBus, but that discussion is outside the scope of this project.
