### ISSUE TITLE
Pending Debian package update

### ISSUE THREAD

**Issue by gunnarhj** [sarim/ibus-avro#145]
Hi @sarim,

For some 'package technical reasons' I would like to do a new upload of `ibus-avro` soon to Debian (and with that Ubuntu) with the latest changes in the repo. It would be nice if you could do a formal release, since it would allow for a more sensible version string in Debian. Otherwise, if you don't think it's worth it, the new Debian version will be `1.1+git20190823-1`.

Please let me know.

**Comment by sarim** [comment]
Not at the computer ATM. I'll take a look when I get to it, probably
tomorrow. Phew, seems like I looked away from this project for a moment and
quite a few months have flown by.... And looks of pending tasks remaining
:(

**Comment by gunnarhj** [comment]
Hi, it's me again. :-/ Waiting for a decision. A new release - maybe `1.1.1` ? - would be better, even if you don't have the time to complete the docs ATM. Or otherwise it would be fine to simply use a gitshot as mentioned above.

**Comment by sarim** [comment]
Sorry for the delay. Made a new release. I just made it 1.2.

**Comment by gunnarhj** [comment]
Thanks! I have just asked a sponsor to upload it to Debian unstable. There are indeed no big changes in the resulting .deb file - the most important thing is the screenshots in the AppStream metainfo file.

But there is another reason why I wanted to do this. Most input method related packages in Debian are maintained by the Debian Input Method Team, and with this upload I make that team the maintainer of the ibus-avro Debian package. That way the team, and not only I, will supervise the package and make sure it's in good shape. And with this upload the debian/ directory in the Debian source gets simpler and easier to grasp for the team members.

Would be nice to see the docs updated soon. In any case I have not seen any Ask Ubuntu questions lately from users who struggle with installing ibus-avro, and that may be an indication that making ibus-avro an official Debian/Ubuntu package has made a difference.

See you.
