### ISSUE TITLE
Avro in keyboard layout other than English.

### ISSUE THREAD

**Issue by haseebmahmud** [sarim/ibus-avro#146]
আমি জার্মান কীবোর্ড ব্যবহার করি। জার্মান কীবোর্ডের সাথে ইংরেজি কীবোর্ডের পার্থক্য রয়েছে। 
পার্থক্যগুলো দেখতে [এখানে ক্লিক করুন](https://worldthruoureyes.com/2015/08/26/difference-between-a-german-vs-an-american-keyboard-yeah-theres-such-a-thing/)। যেমন ইংরেজি কীবোর্ডে যেখানে y সেখানে জার্মান কীবোর্ডে z। প্রশ্নবোধক চিহ্ন, বিসর্গ - এগুলোর অবস্থানও ভিন্ন। আগে এগুলো কোন সমস্যা ছিল না। কারণ অভ্র দিয়ে টাইপ করতে শুরু করলে লোকাল কীবোর্ডের ম্যাপই অনুসরণ করতো। [অভ্রও আইএম](https://avro.im/) সাইটটাও এরকম। কিন্তু (আমার ধারণা) অভ্র ডেব প্যাকেজ আকারে আসার পর অভ্র জার্মান কিবোর্ডের বদলে ইংরেজি কিবোর্ডের ম্যাপিং ফলো করছে। ভিন্ন কীবোর্ডে অভ্যস্ত ব্যবহারকারিদের জন্য এটা খুব অসুবিধাজনক। ব্যক্তিগতভাবে আমি এতে এতোই অসুবিধা বোধ করছি যে আমি [অভ্র আইএম](https://avro.im/) সাইট ব্যবহার করি টাইপ করার জন্য। 

এই অসুবিধা থেকে পরিত্রাণের উপায় কী?

সম্পর্কিত অন্যান্য তথ্য
OS: KUBUNTU 20.04
(যদ্দুর মনে পড়ে উইন্ডোজেও এই সমস্যা দেখেছি। )
Keyboards: German, Bangla (Avro) latest build from repo.

**Comment by gunnarhj** [comment]
I don't understand what you wrote, but want to mention that you can change the layout value in the `/usr/share/ibus/component/ibus-avro.xml` file. If you change it from `us` to `default`, your German layout will be used behind the scenes.

P.S. Avro Phonetic is available in the Ubuntu archive nowadays:

    sudo apt install ibus-avro

**Comment by sarim** [comment]
@gunnarhj I was just coming to comment the same thing. He wrote that he uses a german keyboard, and ibus-avro's previous version didn't have the problem, it used to follow local (in his case german) layout. But the version in official repository uses "us" layout, which makes it troublesome for him to write.

@haseebmahmud Please follow gunnarhj's instruction about editing that xml file. You have to restart ibus-avro after editing, just to be sure just logout login again or restart your pc :)

**Comment by haseebmahmud** [comment]
@gunnarhj Thank you for your reply. It works like a charm. I have changed `us` to `de`. It works too. 
@sarim Thanks.

**Comment by gunnarhj** [comment]
@sarim: I suppose that the possibility to change the layout to your liking is something which would fit well in the docs.

**Comment by haseebmahmud** [comment]
Just wondering how to do the same in Windows. I don't see this file in Windows. Or I am missing something?

**Comment by apandada1** [comment]
> Just wondering how to do the same in Windows. I don't see this file in Windows. Or I am missing something?

This question would be better suited in https://github.com/mugli/Avro-Keyboard, because the Windows version of Avro Keyboard does not use ibus.

**Comment by sarim** [comment]
@haseebmahmud Windows version's implementation is completely different. I don't think it'd be that easy, also there is no input engine or anything in windows. The app listens to keyboard events directly.
