### ISSUE TITLE
Please provide a word frequency text file.

### ISSUE THREAD

**Issue by Oymate** [sarim/ibus-avro#153]
It would helpful if you could provide a word frequency text file.

**Comment by oritromax** [comment]
Please provide more information regarding what you need and for what so we can accommodate your request.

**Comment by Oymate** [comment]
I am trying to locate a Bangla dictionary file for use in an open project 'Open Board:https://github.com/dslul/openboard' . It aims to be an open source replacement for other keyboards on F-droid. Unfortunately the Bangla dictionary files are not up to par, so we need a dictionary file.

TL;DR We need a dictionary file for an open android keyboard.
