### ISSUE TITLE
ibus-avro in Elementary OS

### ISSUE THREAD

**Issue by AnupamMitra** [sarim/ibus-avro#154]
I have installed ibus-Avro in Elementary OS. But when I am typing in bengali in Libre Office Writer or in browser nothing is coming out. Though pressing Ctrl+Space Bar I could toggle between English and Avro (Bengali). But when I choose English for typing, there is no problem. Did I make any mistake?

**Comment by gunnarhj** [comment]
Is `ibus-daemon` running?
Did you set the IM related environment variables?

**Comment by AnupamMitra** [comment]
> Is `ibus-daemon` running?
> Did you set the IM related environment variables?

Thanks for your support.
Yes, ibus-daemon is running. The outcome : ```
anupam@anupam-VirtualBox:~$ ibus-daemon
current session already has an ibus-daemon.
```
Did you mean Input Method? If so, yes, in ibus preferences Avro Phonetic has been
![Screenshot from 2020-10-15 23-52-58](https://user-images.githubusercontent.com/7334823/96170833-bb06ad80-0f41-11eb-9f40-a1ed6ed5628b.png)
 added.

**Comment by gunnarhj** [comment]
No I meant the environment variables. If you run this terminal command:

    env | grep -E 'XMOD|_IM'

it should at least list these variables:

    XMODIFIERS=@im=ibus
    QT_IM_MODULE=ibus
    GTK_IM_MODULE=ibus

**Comment by AnupamMitra** [comment]
> No I meant the environment variables. If you run this terminal command:
> 
> ```
> env | grep -E 'XMOD|_IM'
> ```
> 
> it should at least list these variables:
> 
> ```
> XMODIFIERS=@im=ibus
> QT_IM_MODULE=ibus
> GTK_IM_MODULE=ibus
> ```

Thanks @gunnarhj 
Following is the outcome
anupam@anupam-VirtualBox:~$ env | grep -E 'XMOD|_IM'
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
anupam@anupam-VirtualBox:~$ 

It appears that "GTK_IM_MODULE=ibus" is missing. Does it mean that during installation I made some mistake? If so, what to do now?

**Comment by AnupamMitra** [comment]
@gunnarhj At least it appears that I could resolved the issue. I was reading various questions raised on ibus-avro on Github and answers therein. I also read your answer in a question i.e. [](https://github.com/sarim/ibus-avro/issues/149). Then I applied im-config -n ibus in Terminal and now Bengali type is coming on word file and browser. But I'm yet to understand the problem though it is resolved under "Trial & Error" method. 

Would you please enlighten me?

**Comment by gunnarhj** [comment]
@AnupamMitra: I'm not familiar with Elementary OS, but now I understand that it includes `im-config` which certainly is the simplest way to set it up. `im-config` both launches ibus and sets the appropriate environment variables at login.

No, I don't think you made any mistake.

In the future (as from Ubuntu 20.10) `im-config` will start and configure ibus by default, i.e. you won't normally need to do `im-config -n ibus`, but it will just work out of the box.

**Comment by sarim** [comment]
seeing as his system at least has QT_IM_MODULE set. Seems like im-module is there and working. GTK_IM_MODULE env is not set, probably its not installed. 
`sudo apt install ibus-gtk ibus-gtk3` should help. But I'm not familiar with elementary OS either.

**Comment by gunnarhj** [comment]
@sarim: As from Ubuntu 20.04 ibus pulls `ibus-gtk` and `ibus-gtk3` automatically and safely (via a Recommends), so there is no longer a need to install those packages explicitly.

I would suspect that the OP has [gnome-session](https://gitlab.gnome.org/GNOME/gnome-session/-/blob/master/gnome-session/main.c#L577) installed (without having full GNOME i.e. including gnome-shell), which would explain why `QT_IM_MODULE` and `XMODIFIERS` were set.

**Comment by AnupamMitra** [comment]
**@gunnarhj**  Lot of thanks to you for your continuous support. As the issue has been solved, should I close it?

**Comment by gunnarhj** [comment]
@AnupamMitra: You're welcome. Yes, please close it.
