### ISSUE TITLE
Tested in October 2020 on Arch Linux, Manjaro, Debian10, Fedora32, opneSUSE Leap15.2, MX Linux, Elementary OS, Peppermint OS, KDE Neon, Linux Mint

### ISSUE THREAD

**Issue by hasiburman** [sarim/ibus-avro#155]
From May 2020 to October 2020 I have tested this build on Arch Linux, Manjaro, Debian10, Fedora32, opneSUSE Leap15.2, MX Linux, Elementary OS, Peppermint OS, KDE Neon, Linux Mint. 

They all have worked perfectly. 

Additionally  if libibus-1.0-dev in not found don't worry. It is not needed on the distros I tested in 2020. Build without it.

**Comment by gunnarhj** [comment]
> Additionally if libibus-1.0-dev in not found don't worry. It is not needed on the distros I tested in 2020.

It's mentioned to satisfy the `PKG_CHECK_MODULES(ibus, ibus-1.0)` statement in `configure.ac`, but no ibus package is really needed during the build. Probably the presence of ibus itself is sufficient to satisfy the statement.
