### ISSUE TITLE
Can't install ibus-avro on ParrotOS

### ISSUE THREAD

**Issue by Rafiquzzaman420** [sarim/ibus-avro#157]
I can't install ibus-avro with apt or making the file downloaded from **Github** repository . When I tried to install with **apt** it is giving me this error : 
└──╼ $sudo apt install ibus avro
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package avro is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'avro' has no installation candidate
Please help me out. I already used it in fedora, ubuntu & linuxmint. I'm quite new in Parrot....Thanks in advance

**Comment by gunnarhj** [comment]
The package name in Debian/Ubuntu is `ibus-avro` i.e. with a hyphen.

**Comment by Rafiquzzaman420** [comment]
> The package name in Debian/Ubuntu is `ibus-avro` i.e. with a hyphen.

Thanks for your help. That was a childish mistake of mine.Good Luck developing.

**Comment by IbneSaif** [comment]
> The package name in Debian/Ubuntu is `ibus-avro` i.e. with a hyphen.

I don't know brother
