### ISSUE TITLE
failed to install ibus-avro on my linux ubuntu 20.04 distro

### ISSUE THREAD

**Issue by AymanTareq** [sarim/ibus-avro#158]
_===> wget -q http://download.opensuse.org/repositories/home:/sarimkhan/xUbuntu_14.04/Release.key -O- | sudo apt-key add -_
Terminal: **gpg: no valid OpenPGP data found.**
_===> sudo apt-get update_

Terminal: Hit:1 http://packages.microsoft.com/repos/vscode stable InRelease                                               
Hit:2 http://bd.archive.ubuntu.com/ubuntu focal InRelease                                                       
Hit:3 http://bd.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://bd.archive.ubuntu.com/ubuntu focal-backports InRelease
Ign:5 http://download.opensuse.org/repositories/home:/sarimkhan/xUbuntu_14.04 ./ InRelease                                                           
Err:6 http://download.opensuse.org/repositories/home:/sarimkhan/xUbuntu_14.04 ./ Release                                                             
  404  Not Found [IP: 195.135.221.134 80]
Hit:7 http://security.ubuntu.com/ubuntu focal-security InRelease                                                                                     
Hit:8 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease  
Hit:9 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/focal pgadmin4 InRelease
Reading package lists... Done                 
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'http://packages.microsoft.com/repos/vscode stable InRelease' doesn't support architecture 'armhf'
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'http://packages.microsoft.com/repos/vscode stable InRelease' doesn't support architecture 'arm64'
E: The repository 'http://download.opensuse.org/repositories/home:/sarimkhan/xUbuntu_14.04 ./ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

_===> sudo apt-get install ibus-avro-trusty_
Terminal: Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package ibus-avro-trusty is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ibus-avro-trusty' has no installation candidate

**Comment by sarim** [comment]
These are instructions for older ubuntu. As you're are in ubuntu 20.04. Just do

```
sudo apt install ibus-avro
```

**Comment by AymanTareq** [comment]
Thanks , problem solved.
