### ISSUE TITLE
Avro Crashes Very Frequently -- Impossible to Write

### ISSUE THREAD

**Issue by mhasannafi** [sarim/ibus-avro#159]
I have installed Avro in Ubuntu 20.04 LTS day before yesterday. Since then, **the software has been crashing in every, to say, 4-5 letters**. I have to restart the Avro again and again -- so I have just left typing Bengali -- I am typing either English or Banglish (that I hate the most). I came to know this is a common problem for all the users. Please try to resolve the issue.

**Comment by oritromax** [comment]
#156 please take a look. A temporary solution has been put forth by the dev.

**Comment by sarim** [comment]
> the software has been crashing in every, to say, 4-5 letters

Very interesting, while the issue does exist, It has been very hard for me to consistently reproduce it. 



> I came to know this is a common problem for all the users

I'd be very happy to receive detailed feedback from all these users. How and where did you find them? 


I'm going to close this issue, please reply in #156. I encourage everyone to post detailed feedback with logs :)
