### ISSUE TITLE
Ibus-Avro is not showing word suggestions in Ubuntu Budgie

### ISSUE THREAD

**Issue by razi006** [sarim/ibus-avro#166]
I've been using Ibus-Avro for a long time in Ubuntu and Linux Mint. I've switched to Ubuntu Budgie yesterday and facing a problem. I'm highly depended on Bangla typing. So, Ibus-Avro is somewhat essential for me. When I’m typing, it’s not showing word or spell suggestions like it does in Ubuntu. I can’t change the spelling too. And, sometimes, the written words are disappearing when I'm pressing print screen button. What Can I do?

**Comment by razi006** [comment]
Nope. Nothing happened. I'm on 20.04.2 LTS.
![Screenshot from 2021-03-09 22-37-22 croped](https://user-images.githubusercontent.com/50113404/110506062-f7bd8600-8128-11eb-9278-720fb74d5489.png)
![Screenshot from 2021-03-09 22-38-44 cropped](https://user-images.githubusercontent.com/50113404/110506073-f8eeb300-8128-11eb-8cb7-4038c2b74691.png)

**Comment by razi006** [comment]
Okay

**Comment by fossfreedom** [comment]
@gunnarhj sorry - we (UB) have zero knowledge in this area - no idea about how to debug, nor how ibus-avro works.

**Comment by sarim** [comment]
@razi006 so suggestion window isn't appearing but you can write bangla?

**Comment by fossfreedom** [comment]
All - this all sounds like gobbledegook to me (only an english user here I'm afraid).

I found this on the upstream budgie issue tracker - maybe related? https://github.com/solus-project/budgie-desktop/issues/729#issuecomment-321346197

I also found this in the upstream ibus issue tracker https://github.com/ibus/ibus/issues/2038

Again - none of this makes any sense to me since ibus is a mystery to me.

**Comment by razi006** [comment]
> @razi006 so suggestion window isn't appearing but you can write bangla?

I can write... but can't do it properly. Like I'm trying to write 'ki' with ঈ, but it's appearing as 'কই'!! Usually, I fix this kind of problem with suggestion box. But without it...

**Comment by sarim** [comment]
Well up until receiving this issue's notification, I had no idea what "budgie" was either, not sure I fully do now either. "Ubuntu Budgie", "Budgie-Desktop", "Solus-Project" are those different projects? This seems like the distro/DE isn't launching ibus-panel. Which makes it a bug of that DE/distro and should be reported there. If I were making a gnome based desktop environment or linux distribution, making sure ibus is running properly oob would be a top priority task to me :P 

@razi006 I would suggest exploring the issue links @fossfreedom posted above. As its not a issue of ibus-avro project, I'm going to close this. Feel free to continue the discussion about any workaround :)

**Comment by gunnarhj** [comment]
@razi006: Can you please describe the steps you took to set up `ibus-avro`?

I'm asking because Budgie is a bit special. It's a GNOME like desktop environment, but without `gnome-shell`. So Avro Phonetic should be added in Settings, just as on GNOME (i.e. not via `ibus-setup`), but unlike 'true GNOME' you also need to add the _Keyboard Layout_ applet in _Budgie Desktop Settings_.

**Comment by razi006** [comment]
> Well up until receiving this issue's notification, I had no idea what "budgie" was either, not sure I fully do now either. "Ubuntu Budgie", "Budgie-Desktop", "Solus-Project" are those different projects? This seems like the distro/DE isn't launching ibus-panel. Which makes it a bug of that DE/distro and should be reported there. If I were making a gnome based desktop environment or linux distribution, making sure ibus is running properly oob would be a top priority task to me :P
> 
> @razi006 I would suggest exploring the issue links @fossfreedom posted above. As its not a issue of ibus-avro project, I'm going to close this. Feel free to continue the discussion about any workaround :)

I've tried it. But, after running `ibus-daemon -r -d` i got stuck with Bangla and couldn't turn back to English.

**Comment by fossfreedom** [comment]
Is their example code of an "ibus panel" - if upstream can reuse /
modify something already made then this can be resolved quite quickly
hopefully.

**Comment by gunnarhj** [comment]
Maybe best to just suggest the modified start command for now to make it work. (Assuming that creating a Budgie specific ibus panel might take some time...)

**Comment by sarim** [comment]
Yeah, fixing the start command to use ibus's panel is the way to go. As I said, I don't know much about budgie. But from the quick google search it seems like they were trying to implement a different visual style than of gnome-shell's? So I thought if ibus's default panel doesn't visually meshes well with budgie then they can make their own. I believe source for ibus panel is https://github.com/ibus/ibus/tree/master/ui/gtk3.

**Comment by sarim** [comment]
Last time I checked (years ago), by reading ibus documentation, the description of events were clear enough, (or so I thought). Also creating the whole ui from scratch would be a daunting task, that folder contains quite a bit of related stuff. I just want to rewrite the widget that shows up as "suggestion words".

**Comment by razi006** [comment]
> I installed Ubuntu Budgie 20.04.2 in a VM, and can reproduce the issue with no suggestion window.
> 
> GNOME integrates IBus, and starts and configures it automatically if IBus is installed. For that reason (and to avoid very frequent crashes) we recently changed `im-config` so it doesn't do anything in case of IBus on a GNOME desktop. Since Budgie is GNOME like, and claims to be `GNOME` through the `XDG_CURRENT_DESKTOP` environment variable, we did the same for Budgie (see for instance [the Ubuntu bug #1901460](https://launchpad.net/bugs/1901460)).
> 
> GNOME (including Budgie) starts IBus through this command:
> 
> ```
> ibus-daemon --panel disable --xim
> ```
> 
> However, as @sarim pointed out, that `--panel disable` thing prevents the suggestion window from showing up on Budgie (while it works as expected on 'true GNOME' with `gnome-shell`). And it does so not only for `ibus-avro` but for other IBus input methods as well (I saw the same issue with `ibus-libpinyin`). And it's not only Ubuntu Budgie; I see the same thing on Debian in a Budgie session.
> 
> So @fossfreedom, I'd say that this is an upstream Budgie issue. Using the same command for starting IBus as is used on GNOME seems to be wrong. Budgie should probably use:
> 
> ```
> ibus-daemon --daemonize --xim
> ```
> 
> At least that would be one way to deal with the issue.
> 
> It would be possible to work around the issue (again) on Debian/Ubuntu via `im-config`, but TBH I'm really disinclined to do that. The issue seems to be upstream in nature, and affects not only Debian/Ubuntu.
> 
> @razi006: To work around the issue and fix it for yourself on 20.04 right now, you can open the `/usr/share/im-config/data/21_ibus.rc` file for editing and change these lines:
> 
> ```
> if is_gnome; then
>     return
> fi
> ```
> 
> to
> 
> ```
> #if is_gnome; then
> #    return
> #fi
> ```
> 
> (i.e. comment those lines). Then, after next reboot, you will hopefully see the suggestion window.

![Cropped Screenshot from 2021-03-10 13-10-35](https://user-images.githubusercontent.com/50113404/110590675-4e1adb00-81a2-11eb-8757-fbba4d55af4f.png)

**Comment by apandada1** [comment]
@fossfreedom Once this is fixed upstream, please consider if this patch can be backported to Ubuntu Budgie 20.04 as a release in `focal-updates`. That would help thousands of LTS users type non-Latin scripts without upgrading their Ubuntu version.

@gunnarhj Thank you for spending so much time helping so many people worldwide to type their native scripts conveniently.

**Comment by fossfreedom** [comment]
Certainly this will be backported to both 20.04 and 20.10 Ubuntu Budgie
once accepted by upstream and I will try to get it into Debian as well.

**Comment by gunnarhj** [comment]
@razi006: Try this:

    gedit admin:///usr/share/im-config/data/21_ibus.rc

**Comment by gunnarhj** [comment]
@fossfreedom wrote:

> Certainly this will be backported to both 20.04 and 20.10 Ubuntu Budgie
once accepted by upstream and I will try to get it into Debian as well.

I think Debian unstable is a bit urgent, since "Hard Freeze" for Debian 11 happens the day after tomorrow, and the autopkgtest is trivial.

Maybe it's motivated to patch it there now based on your PR, even if it's not yet committed upstream. They won't likely reject your PR. The only thing I can think of is that they might find the `--daemonize` option redundant, but OTOH it doesn't hurt AFAICT. And UbuntuBudgie/budgie-desktop#65 is there already and can be reopened. :)
