### ISSUE TITLE
Not working in Kali Linux

### ISSUE THREAD

**Issue by sairajgemini** [sarim/ibus-avro#171]
I have installed ibus-avro using command
1. sudo apt-get install ibus-avro
2. Restarted
3. Added Avro language from Settings -> Region and Language -> Input Sources
4. Changed language to Avro and typed from keyboard.
5. Only english font is getting typed.

**Comment by gunnarhj** [comment]
Please run these commands and let us know what they output:

    im-config -m

    env | grep -E 'XMOD|_IM'

**Comment by sairajgemini** [comment]
im-config -m

*Output:*
default
missing
ibus

ibus

env | grep -E 'XMOD|_IM'

*Output:*

QT_IM_MODULE=ibus
***@***.***=ibus


Regards,

Saikat

**Comment by sairajgemini** [comment]
It is fixed now. Probably the dependency issue.

I installed series of tools:

1) sudo apt install libibus-1.0-dev automake autoconf make gjs ibus (Did not work)
2) Next, apt-get install ibus-unikey (Did not work)
3) sudo apt-get install ibus-table && sudo apt-get install ibus ibus-pinyin && sudo apt-get install fcitx fcitx-googlepinyin && sudo apt-get install ibus-gtk ibus-gtk3 
4) reboot
5) Next, from terminal I opened up ibus-setup and added Avro and English in the input source

Now, it's working. So not sure which dependency actually fixed the problem and which is not required.

Regards,
Saikat

**Comment by gunnarhj** [comment]
`ibus-avro` depend on `ibus` and `gjs`, so they were already there.

`ibus-gtk` and `ibus-gtk3` must be there, and normally on official Debian and Ubuntu distros they also are since `ibus` **recommend** those. I wonder if the explanation can be that Kali Linux does not install recommended packages by default.

Anyway, good that you made it work.

**Comment by sairajgemini** [comment]
Closing it.

**Comment by sairajgemini** [comment]
Closing it.
