### ISSUE TITLE
Avro not Showing Ibus input source menu(Ubuntu 21.04)

### ISSUE THREAD

**Issue by dipcb05** [sarim/ibus-avro#174]
Recently I have upgraded to Ubuntu 21.04 from Ubuntu 20.04. I have installed Avro, and it shows the version. But when I am going to setup it by Settings -> Region & Language -> Input Sources -> +(add new) -> more.
Here I don't find Bangla (Avro). Please help.

**Comment by gunnarhj** [comment]
Did you log out and log in again after having installed `ibus-avro`?

**Comment by dipcb05** [comment]
Yes. I tried both ways, log in-log out + rebooting

**Comment by dipcb05** [comment]
[https://paste.pics/CBEAW](url)

**Comment by dipcb05** [comment]
[https://paste.pics/CBEB4](url)

**Comment by gunnarhj** [comment]
You probably find Avro in the Other section. After having clicked the + button, there should be three dots in a horizontal row at the bottom (More...). Click that, and at the bottom of the next window there should be an "Other" option, which you should click to reach the third window.

**Comment by dipcb05** [comment]
yes, I found it here generally. but I can't find it after upgrading. 
But I found it in Ibus list. terminal command = ibus list-engine 
Can you help any terminal command to add the input keyboard by terminal

**Comment by gunnarhj** [comment]
Using a terminal command to add an input source is a bit tricky on Ubuntu. Let's explore the UI a bit more first.

If any of the `bn_BD` or `bn_IN` locales has been generated on your machine, Avro should be found in a submenu if you click "Bangla" in the first or second window.

**Comment by dipcb05** [comment]
[https://paste.pics/CBEDG](url)
[https://paste.pics/CBEDK](url)
please look at those

**Comment by gunnarhj** [comment]
I looked. There is a [bug in 21.04](https://launchpad.net/bugs/1925792) which makes it extra complicated.

In the GUI screenshot you are searching in the "Other" window, and there you only see XKB layouts. But before you reach "Other", you should see a "Bangla" option in one of the two first windows. Click that, i.e. do not proceed to "Other".

**Comment by dipcb05** [comment]
thanks a lot , ধন্যবাদ :D

**Comment by dipcb05** [comment]
solved

**Comment by gunnarhj** [comment]
You're welcome. Unfortunately that GNOME GUI is not very well designed to start with, and the bug doesn't make it easier...
