### ISSUE TITLE
downloaded ibus on raspbian os but there's no "bengali" language

### ISSUE THREAD

**Issue by theusurperofnilfgaard** [sarim/ibus-avro#177]
after downloading ibus i went to input method method and selected ibus.Then i went to ibus preferences--> input Method--> add but when typed "b" on search bar the only language avaiable was bulgerian.bengali was missing.no idea what to do.is apt-pinning only way to get it on raspbian?
im no superuser so i might end up breaking up the system.

**Comment by apandada1** [comment]
`ibus-avro` is not available in Raspbian (Debian) Buster. It would be [available](https://packages.debian.org/search?keywords=ibus-avro) in Bullseye and onwards.

Please [compile from source](https://github.com/sarim/ibus-avro#installation) this project after installing `ibus`.

**Comment by apandada1** [comment]
Alternatively, try installing this [.deb package](http://ftp.us.debian.org/debian/pool/main/i/ibus-avro/ibus-avro_1.2-2_all.deb) from Bullseye. Note that I have not tried this method.

However I did compile `ibus-avro` from source on a Raspberry Pi a few years ago, and it worked.

**Comment by theusurperofnilfgaard** [comment]
> `ibus-avro` is not available in Raspbian (Debian) Buster. It would be [available](https://packages.debian.org/search?keywords=ibus-avro) in Bullseye and onwards.
> 
> Please [compile](https://github.com/sarim/ibus-avro#installation) this project from source after installing `ibus` to use ibus-avro.

**Comment by theusurperofnilfgaard** [comment]
>

**Comment by theusurperofnilfgaard** [comment]
> Please [compile](https://github.com/sarim/ibus-avro#installation) this project from source after installing `ibus` to use ibus-avro.

**Comment by theusurperofnilfgaard** [comment]
>Please compile this project from source after installing ibus to use ibus-avro.

i compiled it from the source in the first place and the issue was there.

**Comment by apandada1** [comment]
Click on the three vertical dots to see the unlisted languages. Have a look at this comment for screenshots. https://github.com/sarim/ibus-avro/issues/175#issuecomment-832167576

**Comment by theusurperofnilfgaard** [comment]
>Click on the three vertical dots to see the unlisted languages. Have a look at this comment for screenshots. #175 (comment)

i checked it again and there was no bengali language.

**Comment by theusurperofnilfgaard** [comment]
>Also, you may have to restart before it appears in the list.

after first time i compile it?

**Comment by gunnarhj** [comment]
@apandada1 wrote:
> `ibus-avro` is not available in Raspbian (Debian) Buster. It would be [available](https://packages.debian.org/search?keywords=ibus-avro) in Bullseye and onwards.

If it incidentally is Raspbian Testing, `ibus-avro` should be there and you can just do:

    sudo apt install ibus-avro

@theusurperofnilfgaard wrote:
> bengali was missing

If the IBus version is > 1.5.21 it's shown as "Bangla" in the list instead of "Bengali".

**Comment by theusurperofnilfgaard** [comment]
First i installed the .dev package from apandada1 and did 
```sudo apt install ibus-avro``` .The output was:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ibus-avro is already the newest version (1.2-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
then i clicked ibus preferences which gave me dialog box saying "The IBus daemon is not running . Do you wish to run it?" i clicked yes and another dialog box said "IBus daemon could not be started in 5 seconds"

later i went to terminal and typed ```ibus``` and there was a option called ```ibus restart``` which claimed to "restart IBus daemon" i did it and here's the output:
```
Can't connect to IBus.
```
i dont know what to do now.

**Comment by theusurperofnilfgaard** [comment]
i found an identical issue  [https://github.com/ibus/ibus/issues/1973#issue-287328454](url)

**Comment by gunnarhj** [comment]
> i dont know what to do now.

I would suggest that you install the `im-config` package if it's not installed already (and then reboot).

    sudo apt install im-config

That's a Debian package which should launch `ibus-daemon` at login and set some related environment variables.

**Comment by theusurperofnilfgaard** [comment]
>I would suggest that you install the im-config package if it's not installed already (and then reboot)

it was already installed.

>Did you also rename /usr/bin/ibus-daemon to /usr/bin/ibus-daemon.bak?

so i went to  `/usr/bin` and did `ls *ibus*` .the output was :
``` 
ibus  ibus-daemon  ibus-setup

```
no,i didn't rename it.what that'd do?

**Comment by gunnarhj** [comment]
>> Did you also rename /usr/bin/ibus-daemon to /usr/bin/ibus-daemon.bak?
>
> so i went to /usr/bin and did ls *ibus* .the output was :
> 
> ibus  ibus-daemon  ibus-setup
> 
> no,i didn't rename it.what that'd do?

Well, you claimed that you found an identical issue, and I noticed that the author of that issue had renamed `ibus-daemon` which probably explained their problem. ;)

As regards `im-config`: Can you please show the output of this command:

    im-config -m

**Comment by theusurperofnilfgaard** [comment]
>As regards im-config: Can you please show the output of this command:

here it is :

```
default
ibus
ibus

```

**Comment by gunnarhj** [comment]
It's odd that there is nothing between `default` and the first `ibus`. Do you have an `~/.xinputrc` file? If you have, please remove it, reboot, and let us know if it makes a difference.

**Comment by theusurperofnilfgaard** [comment]
i did it and heres the output:
```
default
missing
ibus

ibus

```

**Comment by gunnarhj** [comment]
That looks better. Does possibly `ibus-daemon` run now? What's the output of:

    ps x | grep ibus

**Comment by theusurperofnilfgaard** [comment]
output:
```
 6337 pts/0    S+     0:00 grep --color=auto ibus
```
btw i forgot to say thanks for helping me out of this.
thank you for looking into this matter.

**Comment by theusurperofnilfgaard** [comment]
same issue?
https://archived.forum.manjaro.org/t/i-want-ibus-daemon-to-run-all-the-time/105414

**Comment by gunnarhj** [comment]
So `ibus-daemon` is still not running, which is a mystery. Then try to start it manually:

    ibus-daemon -dx

If that command succeeds you should be able to open `ibus-setup` and add Avro as an input method.

Btw, can you also show us the output of this command:

    env | grep -E 'XMOD|_IM'

> same issue?
> https://archived.forum.manjaro.org/t/i-want-ibus-daemon-to-run-all-the-time/105414

Can't really tell. Others with similar difficulties indeed. As regards the problem described in the beginning of that page, I have [reported it to IBus upstream](https://github.com/ibus/ibus/issues/2316).

**Comment by theusurperofnilfgaard** [comment]
>If that command succeeds you should be able to open ibus-setup and add Avro as an input method.

it didnt.

here's the output:
```GTK_IM_MODULE=ibus
QT4_IM_MODULE=ibus
XMODIFIERS=@im=ibus
CLUTTER_IM_MODULE=ibus
QT_IM_MODULE=ibus
```

**Comment by gunnarhj** [comment]
>>     ibus-daemon -dx
>>
>> If that command succeeds you should be able to open ibus-setup and add Avro as an input method.
>
> it didnt.

Please show us any error messages you got when running the command.

(At least the related environment variables were set as expected, which confirms that `im-config` is run at login.)

**Comment by theusurperofnilfgaard** [comment]
>Otherwise please show us any error messages you got when running the `ibus-daemon -dx `command.

no,there was no error message .later i did `ps x | grep ibus` which says:
```
1621 pts/0    S+     0:00 grep --color=auto ibus
```
>Well, one possible reason is that a couple of packages are missing.

those packages are up-to-date.

when i did `ibus-setup` ,a dialog box came saying "The IBus daemon is not running . Do you wish to run it?" after i clicked "yes" it the terminal output was:
```
Can not execute default config program

(ibus-setup:5107): IBUS-WARNING **: 00:20:46.727: Unable to connect to ibus: Error receiving data: Connection reset by peer

```
note:"WARNING" was on yellow and time " 00:20:46.727 " was on blue color.i don't know if it means anything.

**Comment by gunnarhj** [comment]
It may be something in your `$HOME` directory. Try this command:

    rm -rf ~/.cache/ibus

and reboot.

**Comment by theusurperofnilfgaard** [comment]
> It may be something in your `$HOME` directory. Try this command:
> 
> ```
> rm -rf ~/.cache/ibus
> ```
> 
> and reboot.

i did it but nothing changed.

**Comment by gunnarhj** [comment]
Then I'm out of ideas. Sorry.

Whatever the problem is, it's not really an `ibus-avro` one, since `ibus-avro` is an IBus plugin, and it's IBus which refuses to start.

**Comment by theusurperofnilfgaard** [comment]
okay.
i'm thinking of reinstalling raspbian.
thanks for looking into this matter so far.
