### ISSUE TITLE
Bug with WPS and MS office

### ISSUE THREAD

**Issue by RUDRA78372** [sarim/ibus-avro#178]
I am using ibus-avro on manjaro xfce, and it works almost fine with the regular applications I use. But when I use WPS office (and a ttf font obviously), avro does not work with it. Same goes for Microsoft Office 2013 (installed using playonlinux). I am running ibus using "ibus-daemon --xim" command, using truetype fonts both in wine and WPS, but the keyboard is not working. I guess there should be some workarounds to make it work but a quick google search did not find me anything working. Any suggestions or fixes are appreciated.

**Comment by apandada1** [comment]
This is a bug with WPS (see https://github.com/ibus/ibus/issues/1753#issuecomment-454769166, https://github.com/OpenBangla/OpenBangla-Keyboard/issues/139), and it is not ibus-avro specific. It should be reported to the WPS community.

The issue with MS office in Wine is also ibus-avro specific bug. You can report it either at the [IBus](https://github.com/ibus/ibus) bug tracker, or at the [Wine bug tracker](https://bugs.winehq.org/).

**Comment by RUDRA78372** [comment]
Thank you. But here in the OpenBangla reference, Bangla can be written but the words appear later and broken. I guess that's still somewhat fine because at least I will be able to see the letters. But here, I am not able to write bangla at all. Any possible workarounds for that?

**Comment by sarim** [comment]
As mentioned, this should be reported in WPS/Wine/Ibus.
