### ISSUE TITLE
Avro stops working after using for a while and have to restart it again and again.

### ISSUE THREAD

**Issue by dr-crazccc** [sarim/ibus-avro#180]
বার বার অভ্র আটকে যাচ্ছে, কাজ করছে না, তখন আবার নতুন করে রিস্টার্ট দিয়ে কাজ করতে হচ্ছে! আমি পেরট ওএস ইউস করছি, কয়েকজন বলছে উবুন্টুতে ও নাকি সেম সমস্যা! এর সমাধান কি? আর স্টেবল উপদেট আসার সম্ভাবনা কতটুকু?

**Comment by apandada1** [comment]
This is a gjs bug, and has been reported at #156, and there not much Avro devs can do about it. But there is a [workaround](https://github.com/sarim/ibus-avro/issues/156#issuecomment-726378060) which improves the behavior.

BTW, as per my experience, certain operating systems (e.g. KDE Neon 20.04) are less affected than other operating systems (e.g. Manjaro XFCE), so you can try switching the OS.
