### ISSUE TITLE
বার বার অভ্র কিবোর্ড কাজ করা বন্ধ হয়ে যাচ্ছে এর সমাধান কি?

### ISSUE THREAD

**Issue by dr-crazccc** [sarim/ibus-avro#181]
বার বার অভ্র আটকে যাচ্ছে, কাজ করছে না, তখন আবার নতুন করে রিস্টার্ট দিয়ে কাজ করতে হচ্ছে! আমি পেরট ওএস ইউস করছি, কয়েকজন বলছে উবুন্টুতে ও নাকি সেম সমস্যা! এর সমাধান কি? আর স্টেবল উপদেট আসার সম্ভাবনা কতটুকু?

**Comment by apandada1** [comment]
This is identical to #180. Please don't create such duplicate issues.
