### ISSUE TITLE
Can't switch to Avro layout on OmegaT or Qt Linguist

### ISSUE THREAD

**Issue by nr072** [sarim/ibus-avro#182]
### Behavior in OmegaT

When typing in the [OmegaT](https://omegat.org/) editor, if I use the keyboard shortcut to switch to Avro layout, the small window at the center of the screen shows that I switched to Avro:

![switching-to-avro-phonetic-while-in-omegat](https://user-images.githubusercontent.com/26773186/125935085-4f71b460-bbed-4905-87f2-0a4844d43733.png)

But the icon in the panel notification area does not change to the Avro logo:

![ibus-icon-in-panel-notification-area](https://user-images.githubusercontent.com/26773186/125935979-98d18c04-3e71-4725-af0e-aa3d4ad52b32.png)

Then, typing in OmegaT produces English letters, not Bengali. But if I just switch to another app (browser, text editor, file manager, etc.) without doing anything to IBus, the icon in the panel immediately changes to Avro's logo and `ibus-avro` starts working as expected.

![avro-logo-in-panel-notification-area](https://user-images.githubusercontent.com/26773186/125936874-a1b4ff96-78c4-4eac-8c72-64eaf0c04574.png)

If I then switch to OmegaT, the logo stays in the panel but `ibus-avro` does not work.

Basically, when OmegaT is the active window, Avro does not work regardless of whether it was active till now.

### Behavior in Qt Linguist

In [Qt Linguist](https://doc.qt.io/qt-5/qtlinguist-index.html), similarly, the small centered window shows that I supposedly switched to Avro layout, but it does not work.

![switching-to-avro-phonetic-while-in-qt-linguist](https://user-images.githubusercontent.com/26773186/125939147-915bb6e9-fabb-41b9-8372-90a65603b41e.png)

`ibus-avro` does not work even after switching to any other app (without changing anything in IBus). It seems as if swicthing to Avro layout has no effect at all while Qt Linguist is open (as opposed to with OmegaT where `ibus-avro` does not work _only_ if OmegaT is the active window).

## Steps

Action | Expectation | Reality
---|---|---
Open OmegaT | |
Use keyboard shortcuts to switch to Avro layout | Panel's icon will change to Avro logo | It doesn't change
Type in the keyboard | Bengali letters will appear | English letters appear
Switch to another app | | Panel's icon changes to Avro logo
Type in the keyboard | Bengali letters will appear | Bengali letters appear
Switch back to OmegaT | |
Type in the keyboard | Bengali letters will appear | English letters appear

Action | Expectation | Reality
---|---|---
Open Qt Linguist | |
Use keyboard shortcuts to switch to Avro layout | Panel's icon will change to Avro logo | It doesn't change
Type in the keyboard | Bengali letters will appear | English letters appear
Switch to another app | |
Type in the keyboard | Bengali letters will appear | English letters appear
Switch back to Qt Linguist | |
Type in the keyboard | Bengali letters will appear | English letters appear

## System information

**Distro**: Ubuntu Studio 20.04 LTS
**Desktop environemnt**: Xfce 4.14
**IBus version**: 1.5.22
**OmegaT version**: 4.3.2
**Qt Linguist**: 5.12.8

**Comment by sarim** [comment]
Please provide output of these commands in terminal
```
ps x | grep ibus
env | grep -E 'XMOD|_IM'
```

**Comment by nr072** [comment]
Output of "`ps x | grep ibus`" is:

```
   1658 ?        Ssl    0:00 ibus-daemon -d
   1809 ?        Sl     0:00 /usr/libexec/ibus-memconf
   1810 ?        Sl     0:00 /usr/libexec/ibus-ui-gtk3
   1814 ?        Sl     0:01 /usr/libexec/ibus-extension-gtk3
   1819 ?        Sl     0:00 /usr/libexec/ibus-portal
   1835 ?        Sl     0:00 /usr/libexec/ibus-engine-simple
   1866 ?        Sl     0:00 gjs --include-path=/usr/share/ibus-avro /usr/share/ibus-avro/main-gjs.js --ibus > /dev/null
   2972 pts/1    S+     0:00 grep --color=auto ibus
```

"`env | grep -E 'XMOD|_IM'`" doesn't have any output.

Don't know if it's relevant: I hadn't add the 3 lines to my `.bashrc` file. Instead, I'd added "`ibus-daemon -d`" to _Session and Startup_ > _Application Autostart_ (which works fine).

**Comment by sarim** [comment]
> Don't know if it's relevant: I hadn't added the 3 lines to my `.bashrc` file. Instead, I'd added "`ibus-daemon -d`" to _Session and Startup_ > _Application Autostart_ (which works fine)

I think this is exactly why your problem is happening. User isn't supposed to run `ibus-daemon` directly. I suggest you do a bit more research about your desktop environment and how to set up Ibus properly in your environment. hint: check `im-config` .

This is not a ibus-avro issue, rather a user error of not configuring ibus properly.

**Comment by nr072** [comment]
Oh, I see!

Thanks for taking the time to check.

**Comment by gunnarhj** [comment]
@nr072: Since you are on Ubuntu, I'd suggest these steps:

- Open _Language Support_ and select "IBus" as the Keyboard input method system.
- Drop that autostart entry (the previous step makes `im-config` start ibus-daemon).
- Relogin.

**Comment by nr072** [comment]
It was solved by:

- Adding the 3 lines of code to my `.bashrc` file,
- Selecting "IBus" as _keyboard input method system_ in _Language Support_,
- Logging out and in again.

Thanks a lot!
