### ISSUE TITLE
Avro is not showing in ibus input method, in fedora 34

### ISSUE THREAD

**Issue by sh40wn** [sarim/ibus-avro#185]
I am using fedora 34. I followed the given instructions and installed ibus. But can't find the AVRO input method. 

![ibus](https://user-images.githubusercontent.com/50747893/134044890-2d3ac6f4-d399-4776-83ad-a9c411dca4d3.png)

**Comment by apandada1** [comment]
Were you able to fix the issue? Can you post the solution so that it helps future users?

**Comment by sh40wn** [comment]
> Were you able to fix the issue? Can you post the solution so that it helps future users?

It was a simple solution. Log out -> Log in ... I forgot to do that.

It works flowlessly.
 
![avro=2](https://user-images.githubusercontent.com/50747893/134052011-65d22000-1781-4cb6-aa06-e8b45f242e20.png)
d
