### ISSUE TITLE
Suddenly stopped working in Ubuntu Unity 20.04 LTS 

### ISSUE THREAD

**Issue by badhanroy420** [sarim/ibus-avro#186]
Hi, I'm using ibus-avro on my Ubuntu 20.04 LTS desktop . And facing a major problem.. When I start typing Bengali it's ok .. but suddenly it's stuck and start typing English. I have tried to switch & switch back . Nothing working . Then I re-install ibus-avro. Same problem remains. But that time , I mean when the problem time .. I also tried to restart ibus . It's work again . And after some time .. same problem again. I don't know what is happening . I just want solution . We love Avro . And we want to use it without any hassle . Thanks in advance . Please solve the issue .

**Comment by sarim** [comment]
see #165

**Comment by sarim** [comment]
see #156
