### ISSUE TITLE
Error installing on Manjaro Gnome 21.2.4

### ISSUE THREAD

**Issue by maacpiash** [sarim/ibus-avro#191]
Running `yay -S ibus-avro-git` yields the following output:

<pre>:: <b>Checking for conflicts...</b>
:: <b>Checking for inner conflicts...</b>
[Aur:1]  ibus-avro-git-1:1.0.r8.gfe50959-1

  1 ibus-avro-git                            (Build Files Exist)
==&gt; Packages to cleanBuild?
==&gt; [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==&gt; A
:: <b>Deleting (1/1): /home/ahad/.cache/yay/ibus-avro-git</b>
:: <b>(1/1) Downloaded PKGBUILD: ibus-avro-git</b>
  1 ibus-avro-git                            (Build Files Exist)
==&gt; Diffs to show?
==&gt; [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==&gt; A

==&gt; Proceed with install? [Y/n] y
:: <b>(1/1) Parsing SRCINFO: ibus-avro-git</b>
<font color="#4E9A06"><b>==&gt;</b></font><b> Making package: ibus-avro-git 1:1.0.r8.gfe50959-1 (Fri 11 Mar 2022 22:48:20)</b>
<font color="#4E9A06"><b>==&gt;</b></font><b> Retrieving sources...</b>
<font color="#3465A4"><b>  -&gt;</b></font><b> Cloning ibus-avro git repo...</b>
Cloning into bare repository &apos;/home/ahad/.cache/yay/ibus-avro-git/ibus-avro&apos;...
remote: Enumerating objects: 1406, done.
remote: Counting objects: 100% (196/196), done.
remote: Compressing objects: 100% (129/129), done.
remote: Total 1406 (delta 88), reused 149 (delta 63), pack-reused 1210
Receiving objects: 100% (1406/1406), 11.42 MiB | 5.56 MiB/s, done.
Resolving deltas: 100% (661/661), done.
<font color="#4E9A06"><b>==&gt;</b></font><b> Validating source files with sha256sums...</b>
    ibus-avro ... Skipped
<font color="#4E9A06"><b>==&gt;</b></font><b> Making package: ibus-avro-git 1:1.0.r8.gfe50959-1 (Fri 11 Mar 2022 22:48:23)</b>
<font color="#4E9A06"><b>==&gt;</b></font><b> Checking runtime dependencies...</b>
<font color="#4E9A06"><b>==&gt;</b></font><b> Checking buildtime dependencies...</b>
<font color="#4E9A06"><b>==&gt;</b></font><b> Retrieving sources...</b>
<font color="#3465A4"><b>  -&gt;</b></font><b> Updating ibus-avro git repo...</b>
Fetching origin
<font color="#4E9A06"><b>==&gt;</b></font><b> Validating source files with sha256sums...</b>
    ibus-avro ... Skipped
<font color="#4E9A06"><b>==&gt;</b></font><b> Removing existing $srcdir/ directory...</b>
<font color="#4E9A06"><b>==&gt;</b></font><b> Extracting sources...</b>
<font color="#3465A4"><b>  -&gt;</b></font><b> Creating working copy of ibus-avro git repo...</b>
Cloning into &apos;ibus-avro&apos;...
done.
<font color="#4E9A06"><b>==&gt;</b></font><b> Starting prepare()...</b>
configure.ac:6: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.
./lib/autoconf/general.m4:2434: AC_DIAGNOSE is expanded from...
aclocal.m4:139: AM_INIT_AUTOMAKE is expanded from...
configure.ac:6: the top level
configure.ac:7: warning: AC_OUTPUT should be used without arguments.
configure.ac:7: You should run autoupdate.
configure.ac:6: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.ac:6: https://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
configure.ac:6: installing &apos;./install-sh&apos;
configure.ac:6: installing &apos;./missing&apos;
<font color="#4E9A06"><b>==&gt;</b></font><b> Starting pkgver()...</b>
<font color="#4E9A06"><b>==&gt;</b></font><b> Updated version: ibus-avro-git 1:1.2.r3.gb93d9de-1</b>
<font color="#4E9A06"><b>==&gt;</b></font><b> Sources are ready.</b>
<font color="#4E9A06"><b>==&gt;</b></font><b> Making package: ibus-avro-git 1:1.2.r3.gb93d9de-1 (Fri 11 Mar 2022 22:48:25)</b>
<font color="#4E9A06"><b>==&gt;</b></font><b> Checking runtime dependencies...</b>
<font color="#4E9A06"><b>==&gt;</b></font><b> Checking buildtime dependencies...</b>
<font color="#C4A000"><b>==&gt; WARNING:</b></font><b> Using existing $srcdir/ tree</b>
<font color="#4E9A06"><b>==&gt;</b></font><b> Starting pkgver()...</b>
<font color="#4E9A06"><b>==&gt;</b></font><b> Starting build()...</b>
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
./configure: line 3658: syntax error near unexpected token `ibus,&apos;
./configure: line 3658: `PKG_CHECK_MODULES(ibus, ibus-1.0)&apos;
<font color="#CC0000"><b>==&gt; ERROR:</b></font><b> A failure occurred in build().</b>
<b>    Aborting...</b>
 -&gt; error making: ibus-avro-git
</pre>

**Comment by apandada1** [comment]
Works for me in EndeavourOS (with yay). Is your Manjaro fully updated? Also, can you try installing with pamac instead?

**Comment by apandada1** [comment]
Builds successfully for me on Manjaro XFCE with pamac.

```
$ pamac build ibus-avro-git
Preparing...
Checking ibus-avro-git dependencies...
Warning: downgrading package ibus-avro-git (1:1.2.r2.g2883b96-1 => 1:1.0.r8.gfe50959-1)
Resolving dependencies...
Checking inter-conflicts...

To build (1):
  ibus-avro-git  1:1.0.r8.gfe50959-1  (1:1.2.r2.g2883b96-1)  AUR


Edit build files : [e] 
Apply transaction ? [e/y/N] y

Cloning ibus-avro-git build files...
Generating ibus-avro-git information...

Building ibus-avro-git...
==> Making package: ibus-avro-git 1:1.0.r8.gfe50959-1 (Friday 11 March 2022 11:19:58 AM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning ibus-avro git repo...
Cloning into bare repository '/var/tmp/pamac-build-archisman/ibus-avro-git/ibus-avro'...
remote: Enumerating objects: 1406, done.
remote: Counting objects: 100% (196/196), done.
remote: Compressing objects: 100% (129/129), done.
remote: Total 1406 (delta 88), reused 149 (delta 63), pack-reused 1210
Receiving objects: 100% (1406/1406), 11.42 MiB | 4.48 MiB/s, done.
Resolving deltas: 100% (661/661), done.
==> Validating source files with sha256sums...
    ibus-avro ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of ibus-avro git repo...
Cloning into 'ibus-avro'...
done.
==> Starting prepare()...
configure.ac:6: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.
./lib/autoconf/general.m4:2434: AC_DIAGNOSE is expanded from...
aclocal.m4:483: AM_INIT_AUTOMAKE is expanded from...
configure.ac:6: the top level
configure.ac:7: warning: AC_OUTPUT should be used without arguments.
configure.ac:7: You should run autoupdate.
configure.ac:6: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.ac:6: https://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
==> Starting pkgver()...
==> Updated version: ibus-avro-git 1:1.2.r3.gb93d9de-1
==> Starting build()...
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ibus... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
\
( \
	libexecdir=/usr/libexec; \
	pkgdatadir=/usr/share/ibus-avro; \
	s=`cat evars.js.in`; \
	eval "echo \"${s}\""; \
) > evars.js
\
( \
	libexecdir=/usr/libexec; \
	pkgdatadir=/usr/share/ibus-avro; \
	s=`cat ibus-avro.xml.in`; \
	eval "echo \"${s}\""; \
) > ibus-avro.xml
\
( \
	libexecdir=/usr/libexec; \
	pkgdatadir=/usr/share/ibus-avro; \
	s=`cat ibus-setup-ibus-avro.desktop.in`; \
	eval "echo \"${s}\""; \
) > ibus-setup-ibus-avro.desktop
==> Entering fakeroot environment...
==> Starting package()...
mkdir -p /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/
mkdir -p /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/libexec/
mkdir -p /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/../glib-2.0/schemas/
mkdir -p /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/../ibus/component/	
mkdir -p /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/../metainfo/
mkdir -p /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/../applications/
/usr/bin/install -c -m 644 evars.js /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/evars.js
/usr/bin/install -c -m 755 main-gjs.js /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/main-gjs.js	
/usr/bin/install -c -m 644 avrolib.js /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/avrolib.js
/usr/bin/install -c -m 644 utf8.js /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/utf8.js
/usr/bin/install -c -m 644 avrodict.js /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/avrodict.js
/usr/bin/install -c -m 644 suffixdict.js /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/suffixdict.js
/usr/bin/install -c -m 644 dbsearch.js /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/dbsearch.js
/usr/bin/install -c -m 644 avroregexlib.js /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/avroregexlib.js
/usr/bin/install -c -m 644 suggestionbuilder.js /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/suggestionbuilder.js
/usr/bin/install -c -m 644 levenshtein.js /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/levenshtein.js
/usr/bin/install -c -m 644 autocorrect.js /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/autocorrect.js
/usr/bin/install -c -m 755 pref.js /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/pref.js
/usr/bin/install -c -m 644 avropref.ui /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/avropref.ui	
/usr/bin/install -c -m 644 avro-bangla.png /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/avro-bangla.png
/usr/bin/install -c -m 644 ibus-avro.xml /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/../ibus/component/ibus-avro.xml
/usr/bin/install -c -m 644 com.omicronlab.avro.gschema.xml /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/../glib-2.0/schemas/com.omicronlab.avro.gschema.xml
/usr/bin/install -c -m 644 com.github.sarim.ibus.avro.metainfo.xml /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/../metainfo/com.github.sarim.ibus.avro.metainfo.xml
/usr/bin/install -c -m 644 ibus-setup-ibus-avro.desktop /var/tmp/pamac-build-archisman/ibus-avro-git/pkg/ibus-avro-git/usr/share/ibus-avro/../applications/ibus-setup-ibus-avro.desktop
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "ibus-avro-git"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: ibus-avro-git 1:1.2.r3.gb93d9de-1 (Friday 11 March 2022 11:20:34 AM)
==> Cleaning up...

Checking keyring...                                                                                                      [1/1]
Checking integrity...                                                                                                    [1/1]
Loading packages files...                                                                                                [1/1]
Checking file conflicts...                                                                                               [1/1]
Checking available disk space...                                                                                         [1/1]
Upgrading ibus-avro-git (1:1.2.r2.g2883b96-1 -> 1:1.2.r3.gb93d9de-1)...                                                  [1/1]
Running post-transaction hooks...
Arming ConditionNeedsUpdate...                                                                                           [1/3]
Compiling GSettings XML schema files...                                                                                  [2/3]
Updating the desktop file MIME type cache...                                                                             [3/3]
Transaction successfully finished.
```

**Comment by maacpiash** [comment]
Thank you, @apandada1. Installation with `pamac` worked for me.
