### ISSUE TITLE
ibus-avro not working

### ISSUE THREAD

**Issue by abirabedinkhan** [sarim/ibus-avro#197]
ibus-avro isn't working on my kali machine. It actually switches to Avro phonetic but it still writes in English.

**Comment by gunnarhj** [comment]
Please run

    env | grep -E 'XMOD|_IM'

and let us know what that command outputs.

**Comment by apandada1** [comment]
May or may not be relevant to the issue, but Kali Linux has a lot of essential background processes disabled, which makes it hard to perform regular tasks in it (It is not meant to be used as a general purpose desktop operating system). 

Please see https://unix.meta.stackexchange.com/questions/5360/why-is-kali-linux-so-hard-to-set-up-why-wont-people-help-me

**Comment by abirabedinkhan** [comment]
> Please run
> 
> ```
> env | grep -E 'XMOD|_IM'
> ```
> 
> and let us know what that command outputs.

```
┌──(abirabedinkhan㉿code)-[~]
└─$ env | grep -E 'XMOD|_IM'

QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus

```

**Comment by gunnarhj** [comment]
>     QT_IM_MODULE=ibus
>     XMODIFIERS=@im=ibus

That should be sufficient provided that you use the GNOME desktop. Otherwise this is needed too:

    GTK_IM_MODULE=ibus

**Comment by abirabedinkhan** [comment]
> > ```
> > QT_IM_MODULE=ibus
> > XMODIFIERS=@im=ibus
> > ```
> 
> That should be sufficient provided that you use the GNOME desktop. Otherwise this is needed too:
> 
> ```
> GTK_IM_MODULE=ibus
> ```

Yes, I am gnome-desktop.

**Comment by abirabedinkhan** [comment]
But Avro is working inside the search light gnome-shell app. But it's not working outside of it

**Comment by gunnarhj** [comment]
Then it's not an `ibus-avro` issue, but it's all about how ibus itself plays with GNOME on your OS. I would test with setting `GTK_IM_MODULE` explicitly anyway.

**Comment by abirabedinkhan** [comment]
How can I set GTK_IM_MODULE=ibus

**Comment by apandada1** [comment]
See "Set environment variable globally". https://fedingo.com/how-to-set-environment-variable-in-ubuntu/

**Comment by abirabedinkhan** [comment]
```
➜  ~ $GTK_IM_MODULE                 
Usage: ibus COMMAND [OPTION...]

Commands:
  engine          Set or get engine
  exit            Exit ibus-daemon
  list-engine     Show available engines
  watch           (Not implemented)
  restart         Restart ibus-daemon
  version         Show version
  read-cache      Show the content of registry cache
  write-cache     Create registry cache
  address         Print the D-Bus address of ibus-daemon
  read-config     Show the configuration values
  reset-config    Reset the configuration values
  emoji           Save emoji on dialog to clipboard
  help            Show this information
➜  ~ $GTK_IM_MODULE engine          
xkb:us::eng
➜  ~ sudo $GTK_IM_MODULE engine ibus

(process:50800): IBUS-CRITICAL **: 18:32:05.174: ibus_bus_set_global_engine: assertion 'IBUS_IS_BUS (bus)' failed
Set global engine failed.

```

**Comment by gunnarhj** [comment]
Please understand that your issue is not with the ibus-avro plugin itself. It's about the configuration of your Kali Linux system, which nobody here seems to know enough about.

Take a look again at @apandada1's comment about Kali Linux. The fact that you need to ask these questions indicates that Kali Linux is not a good choice of OS for you.

**Comment by apandada1** [comment]
> I also not working in ubuntu...

Not sure what you meant. ibus-avro works just fine in Ubuntu, its official flavors, and Mint.
This issue can be closed, since it is not specific to ibus-avro (@sarim).

**Comment by abirabedinkhan** [comment]
after @apandada1  recommendation I replace kali with ubuntu. But still I bus-avro isn't working. 
https://prnt.sc/Y-43ZtaSIF3x

**Comment by gunnarhj** [comment]
Which guide for installing and setting up `ibus-avro` did you follow?

**Comment by abirabedinkhan** [comment]
I did it before on a ubuntu machine before and it worked. 
```
sudo apt-get install ibus-avro
```
I ran this command and added language from keyboard settings Bangla (Avro Phonetic)

**Comment by gunnarhj** [comment]
As a test, can you try with some other IBus engine, for instance `ibus-libpinyn`?

**Comment by abirabedinkhan** [comment]
it's working again. I just reinstall ibus and ibus-avro
