### ISSUE TITLE
Crashes after writing 3-5 words or less than it, I'm unable to write a full sentence

### ISSUE THREAD

**Issue by abkarim** [sarim/ibus-avro#199]
os: q4os (Debian based)
environment: KDE plasma

I'm not sure which word causes this problem. But when I restart it using `ibus restart` it works again and also crashes without any warning or error like previously.

**Comment by gunnarhj** [comment]
Please look at #183, which is a more generally worded crash issue. It includes a request to start `ibus-daemon` from terminal and post the terminal output from the crash in a comment. Your help in that respect would be appreciated.

**Comment by abkarim** [comment]
Thank you, Please check my message in #183 please

**Comment by abkarim** [comment]
My problem is in #156
