### ISSUE TITLE
Can't write Bengali in Visual Studio Code.

### ISSUE THREAD

**Issue by rafiz001** [sarim/ibus-avro#201]
Ibus turns on avro Bengali phonetic, but Bengali characters not appearing in Visual Studio Code. Please Solve this issue.

**Comment by gunnarhj** [comment]
There seems to be an [issue with Visual Studio Code and IBus in general](https://github.com/ibus/ibus/issues/1948). But there is no specific Avro Phonetic problem to solve.

**Comment by gunnarhj** [comment]
Second thought.. I'm on Ubuntu 22.04 and downloaded and installed Visual Studio Code via the .deb file provided at https://code.visualstudio.com . IBus input methods, including Avro Phonetic, work fine.

Before that I tried the snap, and with that IBus didn't work.

So how did you install Visual Studio Code?

**Comment by rafiz001** [comment]
Yeah, I'm running snap version. Ok, let me try with .deb package.

**Comment by sarim** [comment]
https://github.com/microsoft/vscode/issues/96041
