### ISSUE TITLE
Cosmic DE Alpha, couldn't make avro work.. 

### ISSUE THREAD

**Issue by iHarryPotter178** [sarim/ibus-avro#215]
I installed Cosmic Alpha 1, tried ibus-Avro in it.. Restarted ibus.. But can't find the avro in input method.. It worked really well in gnome..
Can the devs look into it.. I also put a bug report on cosmic.. But I think it should just work with ibus..

**Comment by archisman-panigrahi** [comment]
Please ask in the Pop OS forum about how to configure IBus in the Cosmic DE. This is not a ibus-avro bug.

**Comment by iHarryPotter178** [comment]
I did and it seems cosmic doesn't support ibus at all.. It's wayland only and fctx5 is the default.. Closing this with this comment.. Because ibus avro wouldn't work...

**Comment by archisman-panigrahi** [comment]
FYI, Openbangla keyboard has a fcitx5 version https://github.com/OpenBangla/OpenBangla-Keyboard/discussions/213#discussioncomment-715828
