### ISSUE TITLE
need support for arch linux

### ISSUE THREAD

**Issue by ghost** [sarim/ibus-avro#53]
hi, i use manjaro (based on arch). unfortunately there is no system to write bangla :( how can i install avro on manjaro ?

**Comment by apandada1** [comment]
There is an active [AUR](https://aur.archlinux.org/packages/ibus-avro-git/). I have confirmed that it works. You will have to set up the necessary environmental variables after installing.

If you want to help get it into the official Arch repositories, please vote for the AUR package.

@sarim the account of the person who opened this issue has been deleted. It **can be closed**.
