### ISSUE TITLE
Unable to locate package ibus-avro-trusty

### ISSUE THREAD

**Issue by FaisalHaq** [sarim/ibus-avro#62]
I'm unable to install "ibus-avro-trusty" but no problem installing "ibus-avro-saucy"

Added key, sudo apt-get update all done...

user@user-Aspire-4736Z:~$ sudo apt-get install ibus-avro-trusty
[sudo] password for user: 
Reading package lists... Done
Building dependency tree
Reading state information...Done
E: Unable to locate package ibus-avro-trusty

**Comment by SaidulHassan** [comment]
@sarim It's happening here on my LM 17.3. Had have no problem at home with the same distribution but here getting the same error as @FaisalHaq 
```
~ $ sudo apt-get install ibus-avro-trusty
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ibus-avro-trusty
```

> SystemInfo: Linux nt 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
