### ISSUE TITLE
Problem with WINE

### ISSUE THREAD

**Issue by fa7ad** [sarim/ibus-avro#63]
I am running Linux Mint 16 Cinnamon which is a Fork of Ubuntu 13.10. I managed to install ibus-avro-saucy and get it running. And it works perfectly fine on Linux-native apps. The problem I installed MS office 2010 using wine. No matter what I do avro doesn't seem to input text in any of those office apps. it doesn't catch any character besides "space" "tab" and "enter". But, if i copy some bengali text from linux-native apps, it shows little rectangles with a question mark. I tried to install Windows version of Avro inside wine to check if that works. but no... the windows one cant send any character at all. Please check this issue...
Thank You

**Comment by Sobuj53** [comment]
> Actually i solved my issue. I used playonlinux to install MS Office 2010 on Mint. But What i forgot was that playonlinux uses Virtual Drives for each of its installation so any app outside that wineprefix cant touch anything in it. So i went out and installed some truetype bengali fonts. Namely Siyam Rupali and Kalpurush. Then i teaked around and got windows version of avro to install inside the same wineprefix. Now i just have to launch avro(windows) first and then open up ms word. Then i can just press F12 and begin typing in bangla. Sometime if the punctuations (e-kar etc.) dont show up properly. Just change the font and change it back. Hope it helps others. Cheers!!!

vai that's really a elegant solution but the font issue is really disappointing. It always mess up with the `e-kar` I've also installed many avro true type font in my system as well as PlayOnLinux virtual drive's windows folder but it doesn't solve the issue at all :(. Did you you manage to find any workaround for this issue?
