### ISSUE TITLE
[SOLVED] GPG error

### ISSUE THREAD

**Issue by TristanDee** [sarim/ibus-avro#68]
Following the steps at http://linux.omicronlab.com/ubuntu_14.04.html I'm getting an error while trying to add the GPG key. It reads:

wget -q http://download.opensuse.org/repositories/home:/sarimkhan/xUbuntu_14.04/Release.key -o- | sudo apt-key add -
[sudo] password ...: 
gpg: no valid OpenPGP data found.

Knowing that apt-get wouldn't work, I just did and got this error:

W: GPG error: http://download.opensuse.org ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A40A3913512404C1

I googled the gpg error but didn't find any solution. How to resolve the issue, please?

**Comment by eklapothik** [comment]
The key seemed to have gotten expired July 08, 2015. [ Matches with the time of the post exactly one year back :) ]

Can we please have an updated valid key?

**Comment by eklapothik** [comment]
Relevant dump from `sudo apt-key list`
```
pub   1024D/512404C1 2011-02-09 [expired: 2015-07-08]
uid                  home:sarimkhan OBS Project <home:sarimkhan@build.opensuse.org>
```

**Comment by SanaullaParvez** [comment]
First open up Terminal and run the following commands serially- 

___

    1. cd ~/Desktop
 
    2. wget "https://github.com/ugcoder/avro/releases/download/v2.0/avro_2.0-1_all.deb"
    
    2. sudo dpkg -i avro_2.0-1_all.deb
    
    3. sudo apt-get install -fy (now if you see any dependency error, then also run the third command)

___


Avro should be installed on your system by now. 

- Now go to ``Settings`` -> ``Language Support`` 
- Check whether ``ibus`` is selected as the default input method. 

From Terminal restart ibus by typing 

> ``ibus restart``

- Again go to ``Settings`` -> ``Keyboard`` -> ``Text Entry`` 
- Click on the plus(``+``) Button
- Search by ``Avro`` name 
- Click ``Bengali(Avro Phonetic)`` -> ``Add`` 

Now Enjoy ``Avro`` as the the input source.
