### ISSUE TITLE
not installing in ubuntu14.10

### ISSUE THREAD

**Issue by nampaina** [sarim/ibus-avro#82]
hello i insatalled the ubuntu version 14.10 but in here i cant install avro as mentioned in web for ubuntu 14.04. please help us. ubuntu 14.04 is in need of avro.

**Comment by mustafiz012** [comment]
Same here...insatalled Ubuntu 14.10 but there is no compitable ibus-avra version for 14.10...please help...

**Comment by fa7ad** [comment]
Use the trusty version
It works

/close the thread/

**Comment by nampaina** [comment]
the repo--/sarimkhan/xUbuntu_14.04/ never works. tried it a lot. if possible do something. fx this repo. it never gets connected. while giving sudo apt get update after adding the sarimkhan repo it waits for a long time and then says failed to connect (and here stays an ip address).

**Comment by fa7ad** [comment]
Then just install it from the git repo
Thats what i did on Fedora 21

You gotta understand, they dont get paid to do this. And they are short of manpower to compile regularly and maintain a repo

**Comment by nampaina** [comment]
use the git way. it works.
