### ISSUE TITLE
Avro does not work on Ubuntu 14.04

### ISSUE THREAD

**Issue by streetcoder** [sarim/ibus-avro#84]
I installed as instruction of https://github.com/sarim/ibus-avro/issues. I saw that everything installed perfectly but do not find anything in "Text Entry Setting".

So, I took restart and reinstalled for several time. Can you tell me how to fix it?

**Comment by fa7ad** [comment]
compile from source, it works

**Comment by streetcoder** [comment]
Can you tell how to do this?

**Comment by fa7ad** [comment]
follow the process on `README.md` file in the repo

**Comment by raselkhancse** [comment]
I've same problem, avro icon showing me right side corner, still not working in Ubuntu 14.04

**Comment by fa7ad** [comment]
Install all the dependencies include `ibus-gtk` and then compile from source and install. Should work...
I installed on a Ubuntu machine this week and its working

**Comment by streetcoder** [comment]
I follow the many ways and instruction but wasn't successfull. Later I need to reinstall Ubuntu in some reason. Then I tried to install avro and got successfull. So, I think it is actually Ubuntu issue not Avro that's mean my Ubuntu got customized wrong way in previous installation because I made experiement on it.

**Comment by fa7ad** [comment]
okay, so can you close the issue now?

**Comment by streetcoder** [comment]
Yes of course.
