### ISSUE TITLE
How to install ibus-avro in Fedora 21

### ISSUE THREAD

**Issue by khanmrhasan** [sarim/ibus-avro#87]
I can't install libibus & libibus-dev using yum in Fedora 21. Can anyone help pls ?

**Comment by fa7ad** [comment]
try `ibus-devel`
I think I made RPMs for avro, download them from [here](https://github.com/fa7ad/avro-fedora/releases)

**Comment by khanmrhasan** [comment]
Thank you very much, brother ! I have installed the f21 RPM from your link and it works ! 
Should it works on CentOS 7 brother ?

**Comment by fa7ad** [comment]
I don't know man, I use Fedora :smile:  so good to know, it actually works

**Comment by trjana49** [comment]
I do not use Fedora and I do not know the answer.
