### ISSUE TITLE
Bengali Avro Keyboard not working in Ubuntu 14.04?

### ISSUE THREAD

**Issue by raselkhancse** [sarim/ibus-avro#88]
I've install Ubuntu 14.04 LTS, before my avro working suddenly not working, but showing me avro icon in right side, but can't work , anyone help me ?

![avro](https://cloud.githubusercontent.com/assets/3629264/6880477/57009824-d55d-11e4-9e54-15e1d888ebb9.png)

**Comment by sarim** [comment]
run this in terminal 
```
rm ~/.candidate-selections.json
```
restart your computer and try again.

**Comment by raselkhancse** [comment]
I'll check
