### ISSUE TITLE
can't find option avro phonetic

### ISSUE THREAD

**Issue by Jalal14** [sarim/ibus-avro#90]
i have successfully installed avro but can't find avro phonetic option, but bangla (india)boishakhi,provati and etc are available

**Comment by moni-roy** [comment]
It need to restart PC..

**Comment by Jalal14** [comment]
still not working...
and also can't uninstall avro,please tell me how to uninstall?

**Comment by moni-roy** [comment]
What is your distro??.. Its may help... 
http://linux.omicronlab.com/ 

Check here according to your distro.

**Comment by Jalal14** [comment]
tnx,it's working. :+1:
